/*
 *	autogen/server/zone/objects/area/areashapes/AreaShape.h generated by engine3 IDL compiler 0.70
 */

#ifndef AREASHAPE_H_
#define AREASHAPE_H_

#include "engine/core/Core.h"

#include "engine/core/ManagedReference.h"

#include "engine/core/ManagedWeakReference.h"

#include "system/util/Optional.h"

#ifndef likely
#ifdef __GNUC__
#define likely(x)       __builtin_expect(!!(x), 1)
#define unlikely(x)     __builtin_expect(!!(x), 0)
#else
#define likely(x)       (x)
#define unlikely(x)     (x)
#endif
#endif
#include "engine/util/json_utils.h"

#include "gmock/gmock.h"

#include "engine/core/ManagedObject.h"

#include "engine/util/u3d/Vector3.h"

#include "engine/log/Logger.h"

namespace server {
namespace zone {
namespace objects {
namespace area {
namespace areashapes {

class AreaShape : public ManagedObject {
public:
	/** Constructor */
	AreaShape();

	/**
	 * Set the area center.
	 * @param x the x coordinate.
	 * @param y the y coordinate.
	 */
	void setAreaCenter(float x, float y);

	/**
	 * Set the area center.
	 * @param x the x coordinate.
	 * @param y the y coordinate.
	 * @paran z the z coordinate.
	 */
	void setAreaCenter(float x, float z, float y);

	/**
	 * Get the area center.
	 * @return the area center.
	 */
	Vector3 getAreaCenter() const;

	/**
	 * Check if the coordinate is within the area shape.
	 * @param x the x coordinate.
	 * @param y the y coordinate.
	 * @return true if the coordinate is within the area shape.
	 */
	bool containsPoint(float x, float y) const;

	/**
	 * Check if the coordinate is within the area shape.
	 * @param x the x coordinate.
	 * @param y the y coordinate.
	 * @param z the z coordinate.
	 * @return true if the coordinate is within the area shape.
	 */
	bool containsPoint(float x, float z, float y) const;

	/**
	 * Check if the coordinate is within the area shape.
	 * @param point the point to check if it is within the area shape.
	 * @return true if the coordinate is within the area shape.
	 */
	virtual bool containsPoint(const Vector3& point) const;

	/**
	 * Get the minimum radius of a circle bounding the area shape.
	 * @return the minimum bonding radius.
	 */
	float getRadius() const;

	/**
	 * Generate a random position within the area.
	 * @return a random position within the area.
	 */
	Vector3 getRandomPosition() const;

	/**
	 * Generate a random position within the area with the supplied origin and radius as limits.
	 * @param origin the origin coordinate to generate the random position from.
	 * @param minDistance the minimum distance from the origin.
	 * @param maxDistance the maximum distance from the origin.
	 * @return a random position within the area.
	 */
	Vector3 getRandomPosition(const Vector3& origin, float minDistance, float maxDistance) const;

	float getWidth() const;

	float getHeight() const;

	float getLength() const;

	/**
	 * Check if this is a circular area shape.
	 * @return true if it is a circular area shape.
	 */
	bool isCircularAreaShape() const;

	/**
	 * Check if this is a rectangular area shape.
	 * @return true if it is a rectangular area shape.
	 */
	bool isRectangularAreaShape() const;

	/**
	 * Check if this is a ring area shape.
	 * @return true if it is a ring area shape.
	 */
	bool isRingAreaShape() const;

	/**
	 * Check if this is a cuboid area shape.
	 * @return true if it is a cuboid area shape.
	 */
	bool isCuboidAreaShape() const;

	/**
	 * Check if this is a sphere area shape.
	 * @return true if it is a sphere area shape.
	 */
	bool isSphereAreaShape() const;

	/**
	 * Check if this area shape intersects with the supplied area shape.
	 * @param areaShape the area shape to check for intersections with.
	 * @return true if the area shapes intersects each other.
	 */
	bool intersectsWith(AreaShape* areaShape) const;

	/**
	 * Get the area of the areaShape.
	 * @return the area of the area shape.
	 */
	float getArea() const;

	DistributedObjectServant* _getImplementation();
	DistributedObjectServant* _getImplementationForRead() const;

	void _setImplementation(DistributedObjectServant* servant);

protected:
	AreaShape(DummyConstructorParameter* param);

	virtual ~AreaShape();

	friend class AreaShapeHelper;
};

} // namespace areashapes
} // namespace area
} // namespace objects
} // namespace zone
} // namespace server

using namespace server::zone::objects::area::areashapes;

namespace server {
namespace zone {
namespace objects {
namespace area {
namespace areashapes {

class AreaShapeImplementation : public ManagedObjectImplementation, public Logger {
protected:
	/** The center coordinate of the area. */
	Vector3 areaCenter;

public:
	AreaShapeImplementation();

	AreaShapeImplementation(DummyConstructorParameter* param);

	/**
	 * Set the area center.
	 * @param x the x coordinate.
	 * @param y the y coordinate.
	 */
	void setAreaCenter(float x, float y);

	/**
	 * Set the area center.
	 * @param x the x coordinate.
	 * @param y the y coordinate.
	 * @paran z the z coordinate.
	 */
	void setAreaCenter(float x, float z, float y);

	/**
	 * Get the area center.
	 * @return the area center.
	 */
	Vector3 getAreaCenter() const;

	/**
	 * Check if the coordinate is within the area shape.
	 * @param x the x coordinate.
	 * @param y the y coordinate.
	 * @return true if the coordinate is within the area shape.
	 */
	virtual bool containsPoint(float x, float y) const;

	/**
	 * Check if the coordinate is within the area shape.
	 * @param x the x coordinate.
	 * @param y the y coordinate.
	 * @param z the z coordinate.
	 * @return true if the coordinate is within the area shape.
	 */
	virtual bool containsPoint(float x, float z, float y) const;

	/**
	 * Check if the coordinate is within the area shape.
	 * @param point the point to check if it is within the area shape.
	 * @return true if the coordinate is within the area shape.
	 */
	virtual bool containsPoint(const Vector3& point) const;

	/**
	 * Get the minimum radius of a circle bounding the area shape.
	 * @return the minimum bonding radius.
	 */
	virtual float getRadius() const;

	/**
	 * Generate a random position within the area.
	 * @return a random position within the area.
	 */
	virtual Vector3 getRandomPosition() const;

	/**
	 * Generate a random position within the area with the supplied origin and radius as limits.
	 * @param origin the origin coordinate to generate the random position from.
	 * @param minDistance the minimum distance from the origin.
	 * @param maxDistance the maximum distance from the origin.
	 * @return a random position within the area.
	 */
	virtual Vector3 getRandomPosition(const Vector3& origin, float minDistance, float maxDistance) const;

	virtual float getWidth() const;

	virtual float getHeight() const;

	virtual float getLength() const;

	/**
	 * Check if this is a circular area shape.
	 * @return true if it is a circular area shape.
	 */
	virtual bool isCircularAreaShape() const;

	/**
	 * Check if this is a rectangular area shape.
	 * @return true if it is a rectangular area shape.
	 */
	virtual bool isRectangularAreaShape() const;

	/**
	 * Check if this is a ring area shape.
	 * @return true if it is a ring area shape.
	 */
	virtual bool isRingAreaShape() const;

	/**
	 * Check if this is a cuboid area shape.
	 * @return true if it is a cuboid area shape.
	 */
	virtual bool isCuboidAreaShape() const;

	/**
	 * Check if this is a sphere area shape.
	 * @return true if it is a sphere area shape.
	 */
	virtual bool isSphereAreaShape() const;

	/**
	 * Check if this area shape intersects with the supplied area shape.
	 * @param areaShape the area shape to check for intersections with.
	 * @return true if the area shapes intersects each other.
	 */
	virtual bool intersectsWith(AreaShape* areaShape) const;

	/**
	 * Get the area of the areaShape.
	 * @return the area of the area shape.
	 */
	virtual float getArea() const;

	WeakReference<AreaShape*> _this;

	operator const AreaShape*();

	DistributedObjectStub* _getStub();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
protected:
	virtual ~AreaShapeImplementation();

	void finalize();

	void _initializeImplementation();

	void _setStub(DistributedObjectStub* stub);

	void lock(bool doLock = true);

	void lock(ManagedObject* obj);

	void rlock(bool doLock = true);

	void wlock(bool doLock = true);

	void wlock(ManagedObject* obj);

	void unlock(bool doLock = true);

	void runlock(bool doLock = true);

	void _serializationHelperMethod();
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);

	friend class AreaShape;
};

class AreaShapeAdapter : public ManagedObjectAdapter {
public:
	AreaShapeAdapter(AreaShape* impl);

	void invokeMethod(sys::uint32 methid, DistributedMethod* method);

	void setAreaCenter(float x, float y);

	void setAreaCenter(float x, float z, float y);

	bool containsPoint(float x, float y) const;

	bool containsPoint(float x, float z, float y) const;

	float getRadius() const;

	float getWidth() const;

	float getHeight() const;

	float getLength() const;

	bool isCircularAreaShape() const;

	bool isRectangularAreaShape() const;

	bool isRingAreaShape() const;

	bool isCuboidAreaShape() const;

	bool isSphereAreaShape() const;

	bool intersectsWith(AreaShape* areaShape) const;

	float getArea() const;

};

class AreaShapeHelper : public DistributedObjectClassHelper, public Singleton<AreaShapeHelper> {
	static AreaShapeHelper* staticInitializer;

public:
	AreaShapeHelper();

	void finalizeHelper();

	DistributedObject* instantiateObject();

	DistributedObjectPOD* instantiatePOD();

	DistributedObjectServant* instantiateServant();

	DistributedObjectAdapter* createAdapter(DistributedObjectStub* obj);

	friend class Singleton<AreaShapeHelper>;
};

class MockAreaShape : public AreaShape {
public:

	MOCK_METHOD1(containsPoint,bool(const Vector3& point));

};

} // namespace areashapes
} // namespace area
} // namespace objects
} // namespace zone
} // namespace server

using namespace server::zone::objects::area::areashapes;

namespace server {
namespace zone {
namespace objects {
namespace area {
namespace areashapes {

class AreaShapePOD : public ManagedObjectPOD {
public:
	Optional<Vector3> areaCenter;

	String _className;
	AreaShapePOD();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);
	void writeObjectCompact(ObjectOutputStream* stream);



	virtual ~AreaShapePOD();

};

} // namespace areashapes
} // namespace area
} // namespace objects
} // namespace zone
} // namespace server

using namespace server::zone::objects::area::areashapes;

#endif /*AREASHAPEPOD_H_*/
