/*
 *	autogen/server/zone/Zone.h generated by engine3 IDL compiler 0.70
 */

#ifndef ZONE_H_
#define ZONE_H_

#include "engine/core/Core.h"

#include "engine/core/ManagedReference.h"

#include "engine/core/ManagedWeakReference.h"

#include "system/util/Optional.h"

#ifndef likely
#ifdef __GNUC__
#define likely(x)       __builtin_expect(!!(x), 1)
#define unlikely(x)     __builtin_expect(!!(x), 0)
#else
#define likely(x)       (x)
#define unlikely(x)     (x)
#endif
#endif
#include "engine/util/json_utils.h"

namespace server {
namespace zone {

class TreeEntry;

class TreeEntryPOD;

} // namespace zone
} // namespace server

using namespace server::zone;

namespace server {
namespace zone {

class ZoneProcessServer;

class ZoneProcessServerPOD;

} // namespace zone
} // namespace server

using namespace server::zone;

namespace server {
namespace zone {
namespace objects {
namespace area {

class ActiveArea;

class ActiveAreaPOD;

} // namespace area
} // namespace objects
} // namespace zone
} // namespace server

using namespace server::zone::objects::area;

namespace server {
namespace zone {
namespace objects {
namespace creature {

class CreatureObject;

class CreatureObjectPOD;

} // namespace creature
} // namespace objects
} // namespace zone
} // namespace server

using namespace server::zone::objects::creature;

namespace server {
namespace zone {
namespace managers {
namespace planet {

class PlanetManager;

class PlanetManagerPOD;

} // namespace planet
} // namespace managers
} // namespace zone
} // namespace server

using namespace server::zone::managers::planet;

namespace server {
namespace zone {
namespace managers {
namespace space {

class SpaceManager;

class SpaceManagerPOD;

} // namespace space
} // namespace managers
} // namespace zone
} // namespace server

using namespace server::zone::managers::space;

namespace server {
namespace zone {
namespace managers {
namespace creature {

class CreatureManager;

class CreatureManagerPOD;

} // namespace creature
} // namespace managers
} // namespace zone
} // namespace server

using namespace server::zone::managers::creature;

namespace server {
namespace zone {
namespace managers {
namespace gcw {

class GCWManager;

class GCWManagerPOD;

} // namespace gcw
} // namespace managers
} // namespace zone
} // namespace server

using namespace server::zone::managers::gcw;

namespace server {
namespace zone {
namespace objects {
namespace tangible {

class TangibleObject;

class TangibleObjectPOD;

} // namespace tangible
} // namespace objects
} // namespace zone
} // namespace server

using namespace server::zone::objects::tangible;

namespace server {
namespace zone {
namespace objects {
namespace pathfinding {

class NavArea;

class NavAreaPOD;

} // namespace pathfinding
} // namespace objects
} // namespace zone
} // namespace server

using namespace server::zone::objects::pathfinding;

namespace server {
namespace zone {

class ActiveAreaQuadTree;

} // namespace zone
} // namespace server

using namespace server::zone;

namespace server {
namespace zone {

class ActiveAreaOctree;

} // namespace zone
} // namespace server

using namespace server::zone;

#include "gmock/gmock.h"

#include "server/chat/room/ChatRoom.h"

#include "server/zone/ZoneServer.h"

#include "server/zone/InRangeObjectsVector.h"

#include "server/zone/ActiveAreasVector.h"

#include "server/zone/managers/object/ObjectMap.h"

#include "server/zone/managers/planet/MapLocationTable.h"

#include "engine/util/u3d/Vector3.h"

#include "server/zone/QuadTreeReference.h"

#include "system/thread/atomic/AtomicBoolean.h"

#include "server/zone/objects/region/CityRegion.h"

#include "server/zone/managers/ship/tasks/ShipObjectTimerTask.h"

#include "system/lang/Time.h"

#include "server/zone/objects/scene/SceneObject.h"

#include "system/util/SortedVector.h"

#include "system/util/SynchronizedSortedVector.h"

#include "system/thread/Mutex.h"

#include "system/thread/atomic/AtomicInteger.h"

namespace server {
namespace zone {

class Zone : public SceneObject {
public:
	Zone(ZoneProcessServer* processor, const String& zoneName);

protected:
	Zone() { }
public:
	void createContainerComponent();

	void initializePrivateData();

	void initializeTransientMembers();

	void startManagers();

	void stopManagers();

	void clearZone();

	void insert(TreeEntry* entry);

	void remove(TreeEntry* entry);

	void update(TreeEntry* entry);

	void inRange(TreeEntry* entry, float range);

	void updateActiveAreas(TangibleObject* tano);

	void addSceneObject(SceneObject* object);

	void dropSceneObject(SceneObject* object);

	int getInRangeSolidObjects(float x, float z, float y, float range, SortedVector<ManagedReference<TreeEntry* > >* objects, bool readLockZone);

	int getInRangeObjects(float x, float z, float y, float range, SortedVector<ManagedReference<TreeEntry* > >* objects, bool readLockZone, bool includeBuildingObjects = true);

	int getInRangeObjects(float x, float z, float y, float range, InRangeObjectsVector* objects, bool readLockZone, bool includeBuildingObjects = true);

	int getInRangePlayers(float x, float z, float y, float range, SortedVector<ManagedReference<TreeEntry* > >* objects);

	int getInRangeActiveAreas(float x, float z, float y, SortedVector<ManagedReference<ActiveArea* > >* objects, bool readLockZone);

	int getInRangeActiveAreas(float x, float z, float y, ActiveAreasVector* objects, bool readLockZone);

	float getHeight(float x, float y);

	float getHeightNoCache(float x, float y);

	Reference<SceneObject* > getNearestPlanetaryObject(SceneObject* object, const String& mapCategory, const String& mapSubCategory);

	int getInRangeNavMeshes(float x, float y, SortedVector<ManagedReference<NavArea* > >* objects, bool readLockZone);

	SortedVector<ManagedReference<SceneObject* > > getPlanetaryObjectList(const String& mapObjectLocationType);

	/**
	 * Registers the object to the planetary map. This also makes the object visible to the find command.
	 * @param object The object to register to the planetary map.
	 */
	void registerObjectWithPlanetaryMap(SceneObject* object);

	/**
	 * Unregisters the object from the planetary map.
	 * @param object The object to unregister from the planetary map.
	 */
	void unregisterObjectWithPlanetaryMap(SceneObject* object);

	bool objectIsValidPlanetaryMapPerformanceLocation(SceneObject* object);

	bool isObjectRegisteredWithPlanetaryMap(SceneObject* object);

	void updatePlanetaryMapIcon(SceneObject* object, byte icon);

	void sendMapLocationsTo(CreatureObject* player);

	/**
	 * These functions return the size of the terrain file for this zone.
	 */
	float getMinX();

	float getMaxX();

	float getMinY();

	float getMaxY();

	void updateCityRegions();

	CreatureManager* getCreatureManager();

	PlanetManager* getPlanetManager();

	SpaceManager* getSpaceManager();

	ActiveAreaQuadTree* getActiveAreaTree();

	void addCityRegionToUpdate(CityRegion* city);

	ActiveAreaOctree* getActiveAreaOctree();

	bool isWithinBoundaries(const Vector3& position);

	float getBoundingRadius();

	float getZoneObjectRange();

	void incrementSpawnedAgents();

	void decrementSpawnedAgents();

	String getZoneName();

	unsigned int getZoneCRC();

	ZoneServer* getZoneServer();

	GCWManager* getGCWManager();

	unsigned long long getGalacticTime() const;

	bool hasManagersStarted();

	bool isZoneCleared() const;

	int getSpawnedAiAgents() const;

	void setPlanetChatRoom(ChatRoom* room);

	ChatRoom* getPlanetChatRoom();

	bool isGroundZone();

	bool isSpaceZone();

	ShipObjectTimerTask* getTimerTask();

	DistributedObjectServant* _getImplementation();
	DistributedObjectServant* _getImplementationForRead() const;

	void _setImplementation(DistributedObjectServant* servant);

protected:
	Zone(DummyConstructorParameter* param);

	virtual ~Zone();

	friend class ZoneHelper;
};

} // namespace zone
} // namespace server

using namespace server::zone;

namespace server {
namespace zone {

class ZoneImplementation : public SceneObjectImplementation {
	ManagedReference<ChatRoom* > planetChatRoom;

protected:
	Time galacticTime;

	Reference<MapLocationTable* > mapLocations;

	AtomicInteger spawnedAiAgents;

	Mutex spawnCountMutex;

	AtomicBoolean managersStarted;

	bool zoneCleared;

	Reference<ObjectMap* > objectMap;

	ManagedReference<ZoneServer* > server;

	String zoneName;

	unsigned int zoneCRC;

	ManagedReference<ZoneProcessServer* > processor;

public:
	ZoneImplementation(ZoneProcessServer* processor, const String& zoneName);

	ZoneImplementation(DummyConstructorParameter* param);

	virtual void createContainerComponent();

	virtual void initializePrivateData();

	virtual void initializeTransientMembers();

	virtual void finalize();

	virtual void startManagers();

	virtual void stopManagers();

	virtual void clearZone();

	virtual void insert(TreeEntry* entry);

	virtual void remove(TreeEntry* entry);

	virtual void update(TreeEntry* entry);

	virtual void inRange(TreeEntry* entry, float range);

	virtual void updateActiveAreas(TangibleObject* tano);

	virtual void addSceneObject(SceneObject* object);

	virtual void dropSceneObject(SceneObject* object);

	virtual int getInRangeSolidObjects(float x, float z, float y, float range, SortedVector<ManagedReference<TreeEntry* > >* objects, bool readLockZone);

	virtual int getInRangeObjects(float x, float z, float y, float range, SortedVector<ManagedReference<TreeEntry* > >* objects, bool readLockZone, bool includeBuildingObjects = true);

	virtual int getInRangeObjects(float x, float z, float y, float range, InRangeObjectsVector* objects, bool readLockZone, bool includeBuildingObjects = true);

	virtual int getInRangePlayers(float x, float z, float y, float range, SortedVector<ManagedReference<TreeEntry* > >* objects);

	virtual int getInRangeActiveAreas(float x, float z, float y, SortedVector<ManagedReference<ActiveArea* > >* objects, bool readLockZone);

	virtual int getInRangeActiveAreas(float x, float z, float y, ActiveAreasVector* objects, bool readLockZone);

	virtual float getHeight(float x, float y);

	virtual float getHeightNoCache(float x, float y);

	virtual Reference<SceneObject* > getNearestPlanetaryObject(SceneObject* object, const String& mapCategory, const String& mapSubCategory);

	virtual int getInRangeNavMeshes(float x, float y, SortedVector<ManagedReference<NavArea* > >* objects, bool readLockZone);

	virtual SortedVector<ManagedReference<SceneObject* > > getPlanetaryObjectList(const String& mapObjectLocationType);

	/**
	 * Registers the object to the planetary map. This also makes the object visible to the find command.
	 * @param object The object to register to the planetary map.
	 */
	virtual void registerObjectWithPlanetaryMap(SceneObject* object);

	/**
	 * Unregisters the object from the planetary map.
	 * @param object The object to unregister from the planetary map.
	 */
	virtual void unregisterObjectWithPlanetaryMap(SceneObject* object);

	virtual bool objectIsValidPlanetaryMapPerformanceLocation(SceneObject* object);

	virtual bool isObjectRegisteredWithPlanetaryMap(SceneObject* object);

	virtual void updatePlanetaryMapIcon(SceneObject* object, byte icon);

	virtual void sendMapLocationsTo(CreatureObject* player);

	/**
	 * These functions return the size of the terrain file for this zone.
	 */
	virtual float getMinX();

	virtual float getMaxX();

	virtual float getMinY();

	virtual float getMaxY();

	virtual void updateCityRegions();

	virtual CreatureManager* getCreatureManager();

	virtual PlanetManager* getPlanetManager();

	virtual SpaceManager* getSpaceManager();

	virtual ActiveAreaQuadTree* getActiveAreaTree();

	virtual void addCityRegionToUpdate(CityRegion* city);

	virtual ActiveAreaOctree* getActiveAreaOctree();

	virtual bool isWithinBoundaries(const Vector3& position);

	virtual float getBoundingRadius();

	virtual float getZoneObjectRange();

	void incrementSpawnedAgents();

	void decrementSpawnedAgents();

private:
	void setZoneName(const String& n);

	void setZoneCRC(unsigned int zoneCrc);

	void setZoneProcessServer(ZoneProcessServer* procServer);

	void setZoneServer(ZoneServer* zoneServ);

public:
	String getZoneName();

	unsigned int getZoneCRC();

	ZoneServer* getZoneServer();

	virtual GCWManager* getGCWManager();

	unsigned long long getGalacticTime() const;

	bool hasManagersStarted();

	bool isZoneCleared() const;

	int getSpawnedAiAgents() const;

	void setPlanetChatRoom(ChatRoom* room);

	ChatRoom* getPlanetChatRoom();

	virtual bool isGroundZone();

	virtual bool isSpaceZone();

	virtual ShipObjectTimerTask* getTimerTask();

	WeakReference<Zone*> _this;

	operator const Zone*();

	DistributedObjectStub* _getStub();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
protected:
	virtual ~ZoneImplementation();

	void _initializeImplementation();

	void _setStub(DistributedObjectStub* stub);

	void lock(bool doLock = true);

	void lock(ManagedObject* obj);

	void rlock(bool doLock = true);

	void wlock(bool doLock = true);

	void wlock(ManagedObject* obj);

	void unlock(bool doLock = true);

	void runlock(bool doLock = true);

	void _serializationHelperMethod();
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);

	friend class Zone;
};

class ZoneAdapter : public SceneObjectAdapter {
public:
	ZoneAdapter(Zone* impl);

	void invokeMethod(sys::uint32 methid, DistributedMethod* method);

	void createContainerComponent();

	void initializePrivateData();

	void initializeTransientMembers();

	void finalize();

	void startManagers();

	void stopManagers();

	void clearZone();

	void updateActiveAreas(TangibleObject* tano);

	void addSceneObject(SceneObject* object);

	void dropSceneObject(SceneObject* object);

	float getHeight(float x, float y);

	float getHeightNoCache(float x, float y);

	Reference<SceneObject* > getNearestPlanetaryObject(SceneObject* object, const String& mapCategory, const String& mapSubCategory);

	void registerObjectWithPlanetaryMap(SceneObject* object);

	void unregisterObjectWithPlanetaryMap(SceneObject* object);

	bool objectIsValidPlanetaryMapPerformanceLocation(SceneObject* object);

	bool isObjectRegisteredWithPlanetaryMap(SceneObject* object);

	void updatePlanetaryMapIcon(SceneObject* object, byte icon);

	void sendMapLocationsTo(CreatureObject* player);

	float getMinX();

	float getMaxX();

	float getMinY();

	float getMaxY();

	void updateCityRegions();

	CreatureManager* getCreatureManager();

	PlanetManager* getPlanetManager();

	SpaceManager* getSpaceManager();

	void addCityRegionToUpdate(CityRegion* city);

	float getBoundingRadius();

	float getZoneObjectRange();

	void incrementSpawnedAgents();

	void decrementSpawnedAgents();

	String getZoneName();

	unsigned int getZoneCRC();

	ZoneServer* getZoneServer();

	GCWManager* getGCWManager();

	unsigned long long getGalacticTime() const;

	bool hasManagersStarted();

	bool isZoneCleared() const;

	int getSpawnedAiAgents() const;

	void setPlanetChatRoom(ChatRoom* room);

	ChatRoom* getPlanetChatRoom();

	bool isGroundZone();

	bool isSpaceZone();

};

class ZoneHelper : public DistributedObjectClassHelper, public Singleton<ZoneHelper> {
	static ZoneHelper* staticInitializer;

public:
	ZoneHelper();

	void finalizeHelper();

	DistributedObject* instantiateObject();

	DistributedObjectPOD* instantiatePOD();

	DistributedObjectServant* instantiateServant();

	DistributedObjectAdapter* createAdapter(DistributedObjectStub* obj);

	friend class Singleton<ZoneHelper>;
};

class MockZone : public Zone {
public:

	MOCK_METHOD2(isInRange,bool(SceneObject* obj, float range));
	MOCK_METHOD1(getSlottedObjects,void(VectorMap<String, ManagedReference<SceneObject* > >& objects));
	MOCK_METHOD1(getDistanceTo,float(SceneObject* object));
	MOCK_METHOD1(getDistanceTo3d,float(SceneObject* object));
	MOCK_METHOD1(getDistanceTo,float(Coordinate* coordinate));
	MOCK_METHOD1(getDistanceTo3d,float(Coordinate* coordinate));
	MOCK_METHOD0(getZone,Zone*());
	MOCK_METHOD0(getZoneUnsafe,Zone*());
	MOCK_METHOD1(getSlottedObject,Reference<SceneObject* >(const String& slot));
	MOCK_METHOD0(getInventory,Reference<SceneObject* >());
	MOCK_METHOD0(getDatapad,Reference<SceneObject* >());
	MOCK_METHOD1(isFacingObject,bool(SceneObject* obj));
	MOCK_METHOD0(getParent,ManagedWeakReference<SceneObject* >());
	MOCK_METHOD0(asCreatureObject,CreatureObject*());
	MOCK_METHOD0(asAiAgent,AiAgent*());
	MOCK_METHOD0(asShipAiAgent,ShipAiAgent*());
	MOCK_METHOD0(asShipObject,ShipObject*());
	MOCK_METHOD0(asSpaceStationObject,SpaceStationObject*());
	MOCK_METHOD0(asCapitalShipObject,CapitalShipObject*());
	MOCK_METHOD0(asPobShip,PobShipObject*());
	MOCK_METHOD0(asMultiPassengerShip,MultiPassengerShipObject*());
	MOCK_METHOD0(asFighterShip,FighterShipObject*());
	MOCK_METHOD0(asTangibleObject,TangibleObject*());
	MOCK_METHOD0(getTemplateRadius,float());

};

} // namespace zone
} // namespace server

using namespace server::zone;

namespace server {
namespace zone {

class ZonePOD : public SceneObjectPOD {
public:
	Optional<AtomicInteger> spawnedAiAgents;

	Optional<String> zoneName;

	Optional<unsigned int> zoneCRC;

	String _className;
	ZonePOD();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);
	void writeObjectCompact(ObjectOutputStream* stream);



	virtual ~ZonePOD();

};

} // namespace zone
} // namespace server

using namespace server::zone;

#endif /*ZONEPOD_H_*/
