/*
 *	autogen/server/zone/ZoneServer.h generated by engine3 IDL compiler 0.70
 */

#ifndef ZONESERVER_H_
#define ZONESERVER_H_

#include "engine/core/Core.h"

#include "engine/core/ManagedReference.h"

#include "engine/core/ManagedWeakReference.h"

#include "system/util/Optional.h"

#ifndef likely
#ifdef __GNUC__
#define likely(x)       __builtin_expect(!!(x), 1)
#define unlikely(x)     __builtin_expect(!!(x), 0)
#else
#define likely(x)       (x)
#define unlikely(x)     (x)
#endif
#endif
#include "engine/util/json_utils.h"

namespace server {
namespace zone {
namespace objects {
namespace scene {

class SceneObject;

class SceneObjectPOD;

} // namespace scene
} // namespace objects
} // namespace zone
} // namespace server

using namespace server::zone::objects::scene;

namespace server {
namespace zone {

class ZoneProcessServer;

class ZoneProcessServerPOD;

} // namespace zone
} // namespace server

using namespace server::zone;

namespace server {
namespace zone {

class ZoneClientSession;

class ZoneClientSessionPOD;

} // namespace zone
} // namespace server

using namespace server::zone;

namespace server {
namespace zone {

class ZoneHandler;

} // namespace zone
} // namespace server

using namespace server::zone;

namespace server {
namespace zone {

class Zone;

class ZonePOD;

} // namespace zone
} // namespace server

using namespace server::zone;

namespace server {
namespace zone {

class GroundZone;

class GroundZonePOD;

} // namespace zone
} // namespace server

using namespace server::zone;

namespace server {
namespace zone {

class SpaceZone;

class SpaceZonePOD;

} // namespace zone
} // namespace server

using namespace server::zone;

namespace server {
namespace chat {

class ChatManager;

class ChatManagerPOD;

} // namespace chat
} // namespace server

using namespace server::chat;

namespace conf {

class ConfigManager;

} // namespace conf

using namespace conf;

namespace server {
namespace zone {
namespace managers {
namespace object {

class ObjectManager;

} // namespace object
} // namespace managers
} // namespace zone
} // namespace server

using namespace server::zone::managers::object;

namespace server {
namespace zone {
namespace managers {
namespace player {

class PlayerManager;

class PlayerManagerPOD;

} // namespace player
} // namespace managers
} // namespace zone
} // namespace server

using namespace server::zone::managers::player;

namespace server {
namespace zone {
namespace managers {
namespace objectcontroller {

class ObjectController;

class ObjectControllerPOD;

} // namespace objectcontroller
} // namespace managers
} // namespace zone
} // namespace server

using namespace server::zone::managers::objectcontroller;

namespace server {
namespace zone {
namespace managers {
namespace radial {

class RadialManager;

class RadialManagerPOD;

} // namespace radial
} // namespace managers
} // namespace zone
} // namespace server

using namespace server::zone::managers::radial;

namespace server {
namespace zone {
namespace managers {
namespace reaction {

class ReactionManager;

class ReactionManagerPOD;

} // namespace reaction
} // namespace managers
} // namespace zone
} // namespace server

using namespace server::zone::managers::reaction;

namespace server {
namespace zone {
namespace managers {
namespace frs {

class FrsManager;

class FrsManagerPOD;

} // namespace frs
} // namespace managers
} // namespace zone
} // namespace server

using namespace server::zone::managers::frs;

namespace server {
namespace zone {
namespace managers {
namespace skill {

class SkillManager;

} // namespace skill
} // namespace managers
} // namespace zone
} // namespace server

using namespace server::zone::managers::skill;

namespace server {
namespace zone {
namespace managers {
namespace resource {

class ResourceManager;

class ResourceManagerPOD;

} // namespace resource
} // namespace managers
} // namespace zone
} // namespace server

using namespace server::zone::managers::resource;

namespace server {
namespace zone {
namespace managers {
namespace crafting {

class CraftingManager;

class CraftingManagerPOD;

} // namespace crafting
} // namespace managers
} // namespace zone
} // namespace server

using namespace server::zone::managers::crafting;

namespace server {
namespace zone {
namespace managers {
namespace loot {

class LootManager;

class LootManagerPOD;

} // namespace loot
} // namespace managers
} // namespace zone
} // namespace server

using namespace server::zone::managers::loot;

namespace server {
namespace zone {
namespace managers {
namespace auction {

class AuctionManager;

class AuctionManagerPOD;

} // namespace auction
} // namespace managers
} // namespace zone
} // namespace server

using namespace server::zone::managers::auction;

namespace server {
namespace zone {
namespace managers {
namespace mission {

class MissionManager;

class MissionManagerPOD;

} // namespace mission
} // namespace managers
} // namespace zone
} // namespace server

using namespace server::zone::managers::mission;

namespace server {
namespace zone {
namespace managers {
namespace stringid {

class StringIdManager;

} // namespace stringid
} // namespace managers
} // namespace zone
} // namespace server

using namespace server::zone::managers::stringid;

namespace server {
namespace zone {
namespace managers {
namespace creature {

class CreatureTemplateManager;

} // namespace creature
} // namespace managers
} // namespace zone
} // namespace server

using namespace server::zone::managers::creature;

namespace server {
namespace zone {
namespace managers {
namespace ship {

class ShipAgentTemplateManager;

} // namespace ship
} // namespace managers
} // namespace zone
} // namespace server

using namespace server::zone::managers::ship;

namespace server {
namespace zone {
namespace managers {
namespace creature {

class DnaManager;

} // namespace creature
} // namespace managers
} // namespace zone
} // namespace server

using namespace server::zone::managers::creature;

namespace server {
namespace zone {
namespace managers {
namespace creature {

class PetManager;

class PetManagerPOD;

} // namespace creature
} // namespace managers
} // namespace zone
} // namespace server

using namespace server::zone::managers::creature;

namespace server {
namespace zone {
namespace managers {
namespace guild {

class GuildManager;

class GuildManagerPOD;

} // namespace guild
} // namespace managers
} // namespace zone
} // namespace server

using namespace server::zone::managers::guild;

namespace server {
namespace zone {
namespace managers {
namespace city {

class CityManager;

class CityManagerPOD;

} // namespace city
} // namespace managers
} // namespace zone
} // namespace server

using namespace server::zone::managers::city;

namespace server {
namespace zone {
namespace managers {
namespace name {

class NameManager;

} // namespace name
} // namespace managers
} // namespace zone
} // namespace server

using namespace server::zone::managers::name;

#include "engine/service/proto/BasePacketHandler.h"

#include "engine/service/DatagramServiceThread.h"

#include "engine/service/Message.h"

#include "engine/core/ManagedService.h"

#include "engine/log/Logger.h"

#include "system/lang/Exception.h"

#include "system/lang/Time.h"

#include "system/util/VectorMap.h"

#include "system/net/Socket.h"

#include "system/net/SocketAddress.h"

#include "system/net/Packet.h"

#include "system/thread/atomic/AtomicInteger.h"

namespace server {
namespace zone {

class ZoneServer : public ManagedService {
public:
	static const int OFFLINE = 0;

	static const int LOADING = 1;

	static const int ONLINE = 2;

	static const int LOCKED = 3;

	static const int SHUTTINGDOWN = 4;

	static const float CLOSEOBJECTRANGE;

	static const float SPACECLOSEOBJECTRANGE;

	static const float CAPITALSHIPRANGE;

	static const float SPACESTATIONRANGE;

	ZoneServer(ConfigManager* config);

	void initializeTransientMembers();

	ZoneClientSession* createConnection(Socket* sock, SocketAddress& addr);

	void initialize();

	void shutdown();

	void startManagers();

	void startGroundZones();

	void startSpaceZones();

	void stopManagers();

	void start(int p, int mconn = 10);

	void stop();

	void clearZones();

	void timedShutdown(int minutes, int flags = 0);

	void handleMessage(ZoneClientSession* client, Packet* message);

	void processMessage(Message* message);

	bool handleError(ZoneClientSession* client, Exception& e);

	void addTotalSentPacket(unsigned int count);

	void addTotalResentPacket(unsigned int count);

	void printInfo();

	String getInfo();

	void printEvents();

	Reference<SceneObject* > getObject(unsigned long long objectID, bool doLock = true);

	Reference<SceneObject* > createObject(unsigned int templateCRC, const String& dbname, int persistenceLevel = 2);

	Reference<SceneObject* > createObject(unsigned int templateCRC, int persistenceLevel = 2, unsigned long long objectID = 0);

	Reference<SceneObject* > createClientObject(unsigned int templateCRC, unsigned long long objectID = 0);

	void updateObjectToDatabase(SceneObject* object);

	void updateObjectToStaticDatabase(SceneObject* object);

	void destroyObjectFromDatabase(unsigned long long objectID);

	void lock(bool doLock = true);

	void unlock(bool doLock = true);

	void fixScheduler();

	void changeUserCap(int amount = 50);

	int getConnectionCount();

	void increaseOnlinePlayers();

	void decreaseOnlinePlayers();

	void increaseTotalDeletedPlayers();

	int getGalaxyID() const;

	String getGalaxyName() const;

	void setGalaxyName(const String& name);

	bool isServerLocked() const;

	bool isServerOnline() const;

	bool isServerOffline() const;

	bool isServerLoading() const;

	bool isServerShuttingDown() const;

	int getServerCap() const;

	int getServerState() const;

	Zone* getZone(const String& terrainName) const;

	/**
	 * Gets a note based on it's position in the zone map.
	 * NOTE: This idx is not to be considered consistent.
	 * @param idx The index in the map to get the zone.
	 */
	Zone* getZone(int idx);

	int getZoneCount() const;

	SpaceZone* getSpaceZone(int idx);

	int getSpaceZoneCount() const;

	int getMaxPlayers() const;

	int getTotalPlayers() const;

	int getDeletedPlayers() const;

	ObjectManager* getObjectManager();

	PlayerManager* getPlayerManager();

	ReactionManager* getReactionManager();

	FrsManager* getFrsManager();

	ChatManager* getChatManager();

	CityManager* getCityManager();

	ObjectController* getObjectController();

	MissionManager* getMissionManager();

	RadialManager* getRadialManager();

	GuildManager* getGuildManager();

	ResourceManager* getResourceManager();

	CraftingManager* getCraftingManager();

	LootManager* getLootManager();

	AuctionManager* getAuctionManager();

	PetManager* getPetManager();

	SkillManager* getSkillManager();

	NameManager* getNameManager();

	Time* getStartTimestamp();

	void setGalaxyID(int galaxyid);

	void setServerState(int state);

	void setShouldDeleteNavAreas(bool b);

	bool shouldDeleteNavAreas() const;

	void setServerStateLocked();

	void setServerStateOnline();

	void setServerStateShuttingDown();

	void loadLoginMessage();

	void changeLoginMessage(const String& motd);

	String getLoginMessage() const;

	DistributedObjectServant* _getImplementation();
	DistributedObjectServant* _getImplementationForRead() const;

	void _setImplementation(DistributedObjectServant* servant);

protected:
	ZoneServer(DummyConstructorParameter* param);

	virtual ~ZoneServer();

	friend class ZoneServerHelper;
};

} // namespace zone
} // namespace server

using namespace server::zone;

namespace server {
namespace zone {

class ZoneServerImplementation : public ManagedServiceImplementation, public Logger {
	Reference<DatagramServiceThread* > datagramService;

	Reference<BasePacketHandler* > phandler;

	Reference<ConfigManager* > configManager;

	Reference<ZoneHandler* > zoneHandler;

	ManagedReference<ZoneProcessServer* > processor;

	Reference<VectorMap<String, ManagedReference<GroundZone* > >* > zones;

	Reference<VectorMap<String, ManagedReference<SpaceZone* > >* > spaceZones;

	Reference<ObjectManager* > objectManager;

	ManagedReference<PlayerManager* > playerManager;

	ManagedReference<ReactionManager* > reactionManager;

	ManagedReference<FrsManager* > frsManager;

	ManagedReference<ChatManager* > chatManager;

	ManagedReference<RadialManager* > radialManager;

	ManagedReference<CityManager* > cityManager;

	ManagedReference<ResourceManager* > resourceManager;

	ManagedReference<CraftingManager* > craftingManager;

	ManagedReference<LootManager* > lootManager;

	ManagedReference<AuctionManager* > auctionManager;

	ManagedReference<MissionManager* > missionManager;

	ManagedReference<GuildManager* > guildManager;

	ManagedReference<PetManager* > petManager;

	bool deleteNavAreas;

	Reference<StringIdManager* > stringIdManager;

	Reference<CreatureTemplateManager* > creatureTemplateManager;

	Reference<ShipAgentTemplateManager* > shipAgentTemplateManager;

	Reference<DnaManager* > dnaManager;

	unsigned long long totalSentPackets;

	int serverCap;

	unsigned long long totalResentPackets;

	AtomicInteger currentPlayers;

	AtomicInteger maximumPlayers;

	AtomicInteger totalPlayers;

	AtomicInteger totalDeletedPlayers;

	AtomicInteger serverState;

	String galaxyName;

	String loginMessage;

	int galaxyID;

	Time startTimestamp;

public:
	static const int OFFLINE = 0;

	static const int LOADING = 1;

	static const int ONLINE = 2;

	static const int LOCKED = 3;

	static const int SHUTTINGDOWN = 4;

	static const float CLOSEOBJECTRANGE;

	static const float SPACECLOSEOBJECTRANGE;

	static const float CAPITALSHIPRANGE;

	static const float SPACESTATIONRANGE;

	ZoneServerImplementation(ConfigManager* config);

	ZoneServerImplementation(DummyConstructorParameter* param);

	void initializeTransientMembers();

	ZoneClientSession* createConnection(Socket* sock, SocketAddress& addr);

private:
	void loadGalaxyName();

public:
	void initialize();

	void shutdown();

	void startManagers();

	void startGroundZones();

	void startSpaceZones();

	void stopManagers();

	void start(int p, int mconn = 10);

	void stop();

	void clearZones();

	void timedShutdown(int minutes, int flags = 0);

	void handleMessage(ZoneClientSession* client, Packet* message);

	void processMessage(Message* message);

	bool handleError(ZoneClientSession* client, Exception& e);

	void addTotalSentPacket(unsigned int count);

	void addTotalResentPacket(unsigned int count);

	void printInfo();

	String getInfo();

	void printEvents();

	Reference<SceneObject* > getObject(unsigned long long objectID, bool doLock = true);

	Reference<SceneObject* > createObject(unsigned int templateCRC, const String& dbname, int persistenceLevel = 2);

	Reference<SceneObject* > createObject(unsigned int templateCRC, int persistenceLevel = 2, unsigned long long objectID = 0);

	Reference<SceneObject* > createClientObject(unsigned int templateCRC, unsigned long long objectID = 0);

	void updateObjectToDatabase(SceneObject* object);

	void updateObjectToStaticDatabase(SceneObject* object);

	void destroyObjectFromDatabase(unsigned long long objectID);

	void lock(bool doLock = true);

	void unlock(bool doLock = true);

	void fixScheduler();

	void changeUserCap(int amount = 50);

	int getConnectionCount();

	void increaseOnlinePlayers();

	void decreaseOnlinePlayers();

	void increaseTotalDeletedPlayers();

	int getGalaxyID() const;

	String getGalaxyName() const;

	void setGalaxyName(const String& name);

	bool isServerLocked() const;

	bool isServerOnline() const;

	bool isServerOffline() const;

	bool isServerLoading() const;

	bool isServerShuttingDown() const;

	int getServerCap() const;

	int getServerState() const;

	Zone* getZone(const String& terrainName) const;

	/**
	 * Gets a note based on it's position in the zone map.
	 * NOTE: This idx is not to be considered consistent.
	 * @param idx The index in the map to get the zone.
	 */
	Zone* getZone(int idx);

	int getZoneCount() const;

	SpaceZone* getSpaceZone(int idx);

	int getSpaceZoneCount() const;

	int getMaxPlayers() const;

	int getTotalPlayers() const;

	int getDeletedPlayers() const;

	ObjectManager* getObjectManager();

	PlayerManager* getPlayerManager();

	ReactionManager* getReactionManager();

	FrsManager* getFrsManager();

	ChatManager* getChatManager();

	CityManager* getCityManager();

	ObjectController* getObjectController();

	MissionManager* getMissionManager();

	RadialManager* getRadialManager();

	GuildManager* getGuildManager();

	ResourceManager* getResourceManager();

	CraftingManager* getCraftingManager();

	LootManager* getLootManager();

	AuctionManager* getAuctionManager();

	PetManager* getPetManager();

	SkillManager* getSkillManager();

	NameManager* getNameManager();

	Time* getStartTimestamp();

	void setGalaxyID(int galaxyid);

	void setServerState(int state);

	void setShouldDeleteNavAreas(bool b);

	bool shouldDeleteNavAreas() const;

	void setServerStateLocked();

	void setServerStateOnline();

	void setServerStateShuttingDown();

	void loadLoginMessage();

	void changeLoginMessage(const String& motd);

	String getLoginMessage() const;

	WeakReference<ZoneServer*> _this;

	operator const ZoneServer*();

	DistributedObjectStub* _getStub();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
protected:
	virtual ~ZoneServerImplementation();

	void finalize();

	void _initializeImplementation();

	void _setStub(DistributedObjectStub* stub);

	void rlock(bool doLock = true);

	void wlock(bool doLock = true);

	void wlock(ManagedObject* obj);

	void runlock(bool doLock = true);

	void _serializationHelperMethod();
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);

	friend class ZoneServer;
};

class ZoneServerAdapter : public ManagedServiceAdapter {
public:
	ZoneServerAdapter(ZoneServer* impl);

	void invokeMethod(sys::uint32 methid, DistributedMethod* method);

	void initializeTransientMembers();

	void initialize();

	void shutdown();

	void startManagers();

	void startGroundZones();

	void startSpaceZones();

	void stopManagers();

	void start(int p, int mconn);

	void stop();

	void clearZones();

	void timedShutdown(int minutes, int flags);

	void addTotalSentPacket(unsigned int count);

	void addTotalResentPacket(unsigned int count);

	void printInfo();

	String getInfo();

	void printEvents();

	Reference<SceneObject* > getObject(unsigned long long objectID, bool doLock);

	Reference<SceneObject* > createObject(unsigned int templateCRC, const String& dbname, int persistenceLevel);

	Reference<SceneObject* > createObject(unsigned int templateCRC, int persistenceLevel, unsigned long long objectID);

	Reference<SceneObject* > createClientObject(unsigned int templateCRC, unsigned long long objectID);

	void updateObjectToDatabase(SceneObject* object);

	void updateObjectToStaticDatabase(SceneObject* object);

	void destroyObjectFromDatabase(unsigned long long objectID);

	void lock(bool doLock);

	void unlock(bool doLock);

	void fixScheduler();

	void changeUserCap(int amount);

	int getConnectionCount();

	void increaseOnlinePlayers();

	void decreaseOnlinePlayers();

	void increaseTotalDeletedPlayers();

	int getGalaxyID() const;

	String getGalaxyName() const;

	void setGalaxyName(const String& name);

	bool isServerLocked() const;

	bool isServerOnline() const;

	bool isServerOffline() const;

	bool isServerLoading() const;

	bool isServerShuttingDown() const;

	int getServerCap() const;

	int getServerState() const;

	Zone* getZone(const String& terrainName) const;

	Zone* getZone(int idx);

	int getZoneCount() const;

	SpaceZone* getSpaceZone(int idx);

	int getSpaceZoneCount() const;

	int getMaxPlayers() const;

	int getTotalPlayers() const;

	int getDeletedPlayers() const;

	PlayerManager* getPlayerManager();

	ReactionManager* getReactionManager();

	FrsManager* getFrsManager();

	ChatManager* getChatManager();

	CityManager* getCityManager();

	ObjectController* getObjectController();

	MissionManager* getMissionManager();

	RadialManager* getRadialManager();

	GuildManager* getGuildManager();

	ResourceManager* getResourceManager();

	CraftingManager* getCraftingManager();

	LootManager* getLootManager();

	AuctionManager* getAuctionManager();

	PetManager* getPetManager();

	void setGalaxyID(int galaxyid);

	void setServerState(int state);

	void setShouldDeleteNavAreas(bool b);

	bool shouldDeleteNavAreas() const;

	void setServerStateLocked();

	void setServerStateOnline();

	void setServerStateShuttingDown();

	void loadLoginMessage();

	void changeLoginMessage(const String& motd);

	String getLoginMessage() const;

};

class ZoneServerHelper : public DistributedObjectClassHelper, public Singleton<ZoneServerHelper> {
	static ZoneServerHelper* staticInitializer;

public:
	ZoneServerHelper();

	void finalizeHelper();

	DistributedObject* instantiateObject();

	DistributedObjectPOD* instantiatePOD();

	DistributedObjectServant* instantiateServant();

	DistributedObjectAdapter* createAdapter(DistributedObjectStub* obj);

	friend class Singleton<ZoneServerHelper>;
};

} // namespace zone
} // namespace server

using namespace server::zone;

namespace server {
namespace zone {

class ZoneServerPOD : public ManagedServicePOD {
public:
	Optional<ManagedReference<PlayerManagerPOD* >> playerManager;

	Optional<ManagedReference<ReactionManagerPOD* >> reactionManager;

	Optional<ManagedReference<FrsManagerPOD* >> frsManager;

	Optional<ManagedReference<ChatManagerPOD* >> chatManager;

	Optional<ManagedReference<RadialManagerPOD* >> radialManager;

	Optional<ManagedReference<CityManagerPOD* >> cityManager;

	Optional<ManagedReference<ResourceManagerPOD* >> resourceManager;

	Optional<ManagedReference<CraftingManagerPOD* >> craftingManager;

	Optional<ManagedReference<LootManagerPOD* >> lootManager;

	Optional<ManagedReference<AuctionManagerPOD* >> auctionManager;

	Optional<ManagedReference<MissionManagerPOD* >> missionManager;

	Optional<ManagedReference<GuildManagerPOD* >> guildManager;

	Optional<ManagedReference<PetManagerPOD* >> petManager;

	Optional<unsigned long long> totalSentPackets;

	Optional<int> serverCap;

	Optional<unsigned long long> totalResentPackets;

	Optional<AtomicInteger> currentPlayers;

	Optional<AtomicInteger> maximumPlayers;

	Optional<AtomicInteger> totalPlayers;

	Optional<AtomicInteger> totalDeletedPlayers;

	Optional<AtomicInteger> serverState;

	Optional<String> galaxyName;

	Optional<String> loginMessage;

	Optional<int> galaxyID;

	Optional<Time> startTimestamp;

	String _className;
	ZoneServerPOD();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);
	void writeObjectCompact(ObjectOutputStream* stream);



	virtual ~ZoneServerPOD();

};

} // namespace zone
} // namespace server

using namespace server::zone;

#endif /*ZONESERVERPOD_H_*/
