/*
 *	autogen/server/zone/objects/player/sessions/PackupStructureSession.h generated by engine3 IDL compiler 0.70
 */

#ifndef PACKUPSTRUCTURESESSION_H_
#define PACKUPSTRUCTURESESSION_H_

#include "engine/core/Core.h"

#include "engine/core/ManagedReference.h"

#include "engine/core/ManagedWeakReference.h"

#include "system/util/Optional.h"

#ifndef likely
#ifdef __GNUC__
#define likely(x)       __builtin_expect(!!(x), 1)
#define unlikely(x)     __builtin_expect(!!(x), 0)
#else
#define likely(x)       (x)
#define unlikely(x)     (x)
#endif
#endif
#include "engine/util/json_utils.h"

namespace server {
namespace zone {
namespace objects {
namespace creature {

class CreatureObject;

class CreatureObjectPOD;

} // namespace creature
} // namespace objects
} // namespace zone
} // namespace server

using namespace server::zone::objects::creature;

namespace server {
namespace zone {
namespace objects {
namespace structure {

class StructureObject;

class StructureObjectPOD;

} // namespace structure
} // namespace objects
} // namespace zone
} // namespace server

using namespace server::zone::objects::structure;

#include "server/zone/objects/scene/SessionFacadeType.h"

#include "engine/util/Facade.h"

namespace server {
namespace zone {
namespace objects {
namespace player {
namespace sessions {

class PackupStructureSession : public Facade {
public:
	PackupStructureSession(CreatureObject* creature, StructureObject* structure);

	bool isPackupCode(unsigned int code);

	int initializeSession();

	int sendPackupCode();

	int packupStructure();

	int cancelSession();

	int clearSession();

	StructureObject* getStructureObject();

	DistributedObjectServant* _getImplementation();
	DistributedObjectServant* _getImplementationForRead() const;

	void _setImplementation(DistributedObjectServant* servant);

protected:
	PackupStructureSession(DummyConstructorParameter* param);

	virtual ~PackupStructureSession();

	friend class PackupStructureSessionHelper;
};

} // namespace sessions
} // namespace player
} // namespace objects
} // namespace zone
} // namespace server

using namespace server::zone::objects::player::sessions;

namespace server {
namespace zone {
namespace objects {
namespace player {
namespace sessions {

class PackupStructureSessionImplementation : public FacadeImplementation {
protected:
	ManagedReference<CreatureObject* > creatureObject;

	ManagedReference<StructureObject* > structureObject;

	unsigned int packupCode;

public:
	PackupStructureSessionImplementation(CreatureObject* creature, StructureObject* structure);

	PackupStructureSessionImplementation(DummyConstructorParameter* param);

	bool isPackupCode(unsigned int code);

	int initializeSession();

	int sendPackupCode();

	int packupStructure();

	int cancelSession();

	int clearSession();

	StructureObject* getStructureObject();

	WeakReference<PackupStructureSession*> _this;

	operator const PackupStructureSession*();

	DistributedObjectStub* _getStub();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
protected:
	virtual ~PackupStructureSessionImplementation();

	void finalize();

	void _initializeImplementation();

	void _setStub(DistributedObjectStub* stub);

	void lock(bool doLock = true);

	void lock(ManagedObject* obj);

	void rlock(bool doLock = true);

	void wlock(bool doLock = true);

	void wlock(ManagedObject* obj);

	void unlock(bool doLock = true);

	void runlock(bool doLock = true);

	void _serializationHelperMethod();
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);

	friend class PackupStructureSession;
};

class PackupStructureSessionAdapter : public FacadeAdapter {
public:
	PackupStructureSessionAdapter(PackupStructureSession* impl);

	void invokeMethod(sys::uint32 methid, DistributedMethod* method);

	bool isPackupCode(unsigned int code);

	int initializeSession();

	int sendPackupCode();

	int packupStructure();

	int cancelSession();

	int clearSession();

	StructureObject* getStructureObject();

};

class PackupStructureSessionHelper : public DistributedObjectClassHelper, public Singleton<PackupStructureSessionHelper> {
	static PackupStructureSessionHelper* staticInitializer;

public:
	PackupStructureSessionHelper();

	void finalizeHelper();

	DistributedObject* instantiateObject();

	DistributedObjectPOD* instantiatePOD();

	DistributedObjectServant* instantiateServant();

	DistributedObjectAdapter* createAdapter(DistributedObjectStub* obj);

	friend class Singleton<PackupStructureSessionHelper>;
};

} // namespace sessions
} // namespace player
} // namespace objects
} // namespace zone
} // namespace server

using namespace server::zone::objects::player::sessions;

namespace server {
namespace zone {
namespace objects {
namespace player {
namespace sessions {

class PackupStructureSessionPOD : public FacadePOD {
public:
	Optional<ManagedReference<CreatureObjectPOD* >> creatureObject;

	Optional<ManagedReference<StructureObjectPOD* >> structureObject;

	Optional<unsigned int> packupCode;

	String _className;
	PackupStructureSessionPOD();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);
	void writeObjectCompact(ObjectOutputStream* stream);



	virtual ~PackupStructureSessionPOD();

};

} // namespace sessions
} // namespace player
} // namespace objects
} // namespace zone
} // namespace server

using namespace server::zone::objects::player::sessions;

#endif /*PACKUPSTRUCTURESESSIONPOD_H_*/
