/*
 *	autogen/server/zone/objects/intangible/IntangibleObject.cpp generated by engine3 IDL compiler 0.70
 */

#include "IntangibleObject.h"

#include "server/zone/packets/scene/AttributeListMessage.h"

#include "server/zone/objects/creature/CreatureObject.h"

/*
 *	IntangibleObjectStub
 */

enum {RPC_FINALIZE__ = 3178238000,RPC_INITIALIZETRANSIENTMEMBERS__,RPC_SENDBASELINESTO__SCENEOBJECT_,RPC_UPDATESTATUS__INT_BOOL_,RPC_SETCUSTOMOBJECTNAME__UNICODESTRING_BOOL_,RPC_SETDATASIZE__FLOAT_BOOL_,RPC_SETITEMIDENTIFIER__STRING_BOOL_,RPC_GETSTATUS__,RPC_GETDATASIZE__,RPC_GETITEMIDENTIFIER__,RPC_ISINTANGIBLEOBJECT__};

IntangibleObject::IntangibleObject() : SceneObject(DummyConstructorParameter::instance()) {
	IntangibleObjectImplementation* _implementation = new IntangibleObjectImplementation();
	_impl = _implementation;
	_impl->_setStub(this);
	_setClassName("IntangibleObject");
}

IntangibleObject::IntangibleObject(DummyConstructorParameter* param) : SceneObject(param) {
	_setClassName("IntangibleObject");
}

IntangibleObject::~IntangibleObject() {
}



void IntangibleObject::initializeTransientMembers() {
	IntangibleObjectImplementation* _implementation = static_cast<IntangibleObjectImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_INITIALIZETRANSIENTMEMBERS__);

		method.executeWithVoidReturn();
	} else {
		_implementation->initializeTransientMembers();
	}
}

void IntangibleObject::loadTemplateData(SharedObjectTemplate* templateData) {
	IntangibleObjectImplementation* _implementation = static_cast<IntangibleObjectImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->loadTemplateData(templateData);
	}
}

void IntangibleObject::sendBaselinesTo(SceneObject* player) {
	IntangibleObjectImplementation* _implementation = static_cast<IntangibleObjectImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_SENDBASELINESTO__SCENEOBJECT_);
		method.addObjectParameter(player);

		method.executeWithVoidReturn();
	} else {
		_implementation->sendBaselinesTo(player);
	}
}

void IntangibleObject::fillAttributeList(AttributeListMessage* msg, CreatureObject* object) {
	IntangibleObjectImplementation* _implementation = static_cast<IntangibleObjectImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->fillAttributeList(msg, object);
	}
}

void IntangibleObject::updateStatus(int newStatus, bool notifyClient) {
	IntangibleObjectImplementation* _implementation = static_cast<IntangibleObjectImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_UPDATESTATUS__INT_BOOL_);
		method.addSignedIntParameter(newStatus);
		method.addBooleanParameter(notifyClient);

		method.executeWithVoidReturn();
	} else {
		assert(this->isLockedByCurrentThread());
		_implementation->updateStatus(newStatus, notifyClient);
	}
}

void IntangibleObject::setCustomObjectName(const UnicodeString& name, bool notifyClient) {
	IntangibleObjectImplementation* _implementation = static_cast<IntangibleObjectImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_SETCUSTOMOBJECTNAME__UNICODESTRING_BOOL_);
		method.addUnicodeParameter(name);
		method.addBooleanParameter(notifyClient);

		method.executeWithVoidReturn();
	} else {
		assert(this->isLockedByCurrentThread());
		_implementation->setCustomObjectName(name, notifyClient);
	}
}

void IntangibleObject::setDataSize(float dataSize, bool notifyClient) {
	IntangibleObjectImplementation* _implementation = static_cast<IntangibleObjectImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_SETDATASIZE__FLOAT_BOOL_);
		method.addFloatParameter(dataSize);
		method.addBooleanParameter(notifyClient);

		method.executeWithVoidReturn();
	} else {
		assert(this->isLockedByCurrentThread());
		_implementation->setDataSize(dataSize, notifyClient);
	}
}

void IntangibleObject::setItemIdentifier(const String& itemName, bool notifyClient) {
	IntangibleObjectImplementation* _implementation = static_cast<IntangibleObjectImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_SETITEMIDENTIFIER__STRING_BOOL_);
		method.addAsciiParameter(itemName);
		method.addBooleanParameter(notifyClient);

		method.executeWithVoidReturn();
	} else {
		assert(this->isLockedByCurrentThread());
		_implementation->setItemIdentifier(itemName, notifyClient);
	}
}

unsigned int IntangibleObject::getStatus() const {
	IntangibleObjectImplementation* _implementation = static_cast<IntangibleObjectImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETSTATUS__);

		return method.executeWithUnsignedIntReturn();
	} else {
		return _implementation->getStatus();
	}
}

float IntangibleObject::getDataSize() const {
	IntangibleObjectImplementation* _implementation = static_cast<IntangibleObjectImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETDATASIZE__);

		return method.executeWithFloatReturn();
	} else {
		return _implementation->getDataSize();
	}
}

String IntangibleObject::getItemIdentifier() const {
	IntangibleObjectImplementation* _implementation = static_cast<IntangibleObjectImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETITEMIDENTIFIER__);

		String _return_getItemIdentifier;
		method.executeWithAsciiReturn(_return_getItemIdentifier);
		return _return_getItemIdentifier;
	} else {
		return _implementation->getItemIdentifier();
	}
}

bool IntangibleObject::isIntangibleObject() {
	IntangibleObjectImplementation* _implementation = static_cast<IntangibleObjectImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_ISINTANGIBLEOBJECT__);

		return method.executeWithBooleanReturn();
	} else {
		return _implementation->isIntangibleObject();
	}
}

DistributedObjectServant* IntangibleObject::_getImplementation() {

	 if (!_updated) _updated = true;
	return _impl;
}

DistributedObjectServant* IntangibleObject::_getImplementationForRead() const {
	return _impl;
}

void IntangibleObject::_setImplementation(DistributedObjectServant* servant) {
	_impl = servant;
}

/*
 *	IntangibleObjectImplementation
 */

IntangibleObjectImplementation::IntangibleObjectImplementation(DummyConstructorParameter* param) : SceneObjectImplementation(param) {
	_initializeImplementation();
}


IntangibleObjectImplementation::~IntangibleObjectImplementation() {
	IntangibleObjectImplementation::finalize();
}


void IntangibleObjectImplementation::_initializeImplementation() {
	_setClassHelper(IntangibleObjectHelper::instance());

	_this = NULL;

	_serializationHelperMethod();
}

void IntangibleObjectImplementation::_setStub(DistributedObjectStub* stub) {
	_this = static_cast<IntangibleObject*>(stub);
	SceneObjectImplementation::_setStub(stub);
}

DistributedObjectStub* IntangibleObjectImplementation::_getStub() {
	return _this.get();
}

IntangibleObjectImplementation::operator const IntangibleObject*() {
	return _this.get();
}

void IntangibleObjectImplementation::lock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->lock(doLock);
}

void IntangibleObjectImplementation::lock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->lock(obj);
}

void IntangibleObjectImplementation::rlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->rlock(doLock);
}

void IntangibleObjectImplementation::wlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->wlock(doLock);
}

void IntangibleObjectImplementation::wlock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->wlock(obj);
}

void IntangibleObjectImplementation::unlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->unlock(doLock);
}

void IntangibleObjectImplementation::runlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->runlock(doLock);
}

void IntangibleObjectImplementation::_serializationHelperMethod() {
	SceneObjectImplementation::_serializationHelperMethod();

	_setClassName("IntangibleObject");

}

void IntangibleObjectImplementation::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(IntangibleObjectImplementation::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

	initializeTransientMembers();
}

bool IntangibleObjectImplementation::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (SceneObjectImplementation::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	case 0xca41f7e6: //IntangibleObject.status
		TypeInfo<unsigned int >::parseFromBinaryStream(&status, stream);
		return true;

	case 0xb5fd3566: //IntangibleObject.datapadSize
		TypeInfo<float >::parseFromBinaryStream(&datapadSize, stream);
		return true;

	case 0xc8d420ff: //IntangibleObject.itemIdentifier
		TypeInfo<String >::parseFromBinaryStream(&itemIdentifier, stream);
		return true;

	}

	return false;
}

void IntangibleObjectImplementation::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = IntangibleObjectImplementation::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int IntangibleObjectImplementation::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = SceneObjectImplementation::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;
	_nameHashCode = 0xca41f7e6; //IntangibleObject.status
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<unsigned int >::toBinaryStream(&status, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0xb5fd3566; //IntangibleObject.datapadSize
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&datapadSize, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0xc8d420ff; //IntangibleObject.itemIdentifier
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<String >::toBinaryStream(&itemIdentifier, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;


	return _count;
}

void IntangibleObjectImplementation::writeJSON(nlohmann::json& j) {
	SceneObjectImplementation::writeJSON(j);

	nlohmann::json thisObject = nlohmann::json::object();
	thisObject["status"] = status;

	thisObject["datapadSize"] = datapadSize;

	thisObject["itemIdentifier"] = itemIdentifier;

	j["IntangibleObject"] = thisObject;
}

IntangibleObjectImplementation::IntangibleObjectImplementation() {
	_initializeImplementation();
	// server/zone/objects/intangible/IntangibleObject.idl():  		Logger.setLoggingName("IntangibleObject");
	Logger::setLoggingName("IntangibleObject");
	// server/zone/objects/intangible/IntangibleObject.idl():  		status = 0;
	status = 0;
	// server/zone/objects/intangible/IntangibleObject.idl():  		datapadSize = 0;
	datapadSize = 0;
	// server/zone/objects/intangible/IntangibleObject.idl():  		itemIdentifier = "";
	itemIdentifier = "";
	// server/zone/objects/intangible/IntangibleObject.idl():  		super.setContainerInheritPermissionsFromParent(false);
	SceneObjectImplementation::setContainerInheritPermissionsFromParent(false);
	// server/zone/objects/intangible/IntangibleObject.idl():  		super.setContainerDefaultDenyPermission(ContainerPermissions.MOVECONTAINER);
	SceneObjectImplementation::setContainerDefaultDenyPermission(ContainerPermissions::MOVECONTAINER);
	// server/zone/objects/intangible/IntangibleObject.idl():  		super.setContainerDenyPermission("owner", ContainerPermissions.MOVECONTAINER);
	SceneObjectImplementation::setContainerDenyPermission("owner", ContainerPermissions::MOVECONTAINER);
}

void IntangibleObjectImplementation::finalize() {
}

void IntangibleObjectImplementation::loadTemplateData(SharedObjectTemplate* templateData) {
	// server/zone/objects/intangible/IntangibleObject.idl():  		super.loadTemplateData(templateData);
	SceneObjectImplementation::loadTemplateData(templateData);
}

unsigned int IntangibleObjectImplementation::getStatus() const{
	// server/zone/objects/intangible/IntangibleObject.idl():  		return status;
	return status;
}

float IntangibleObjectImplementation::getDataSize() const{
	// server/zone/objects/intangible/IntangibleObject.idl():  		return datapadSize;
	return datapadSize;
}

String IntangibleObjectImplementation::getItemIdentifier() const{
	// server/zone/objects/intangible/IntangibleObject.idl():  		return itemIdentifier;
	return itemIdentifier;
}

bool IntangibleObjectImplementation::isIntangibleObject() {
	// server/zone/objects/intangible/IntangibleObject.idl():  		return true;
	return true;
}

/*
 *	IntangibleObjectAdapter
 */


#include "engine/orb/messages/InvokeMethodMessage.h"


IntangibleObjectAdapter::IntangibleObjectAdapter(IntangibleObject* obj) : SceneObjectAdapter(obj) {
}

void IntangibleObjectAdapter::invokeMethod(uint32 methid, DistributedMethod* inv) {
	DOBMessage* resp = inv->getInvocationMessage();

	switch (methid) {
	case RPC_FINALIZE__:
		{
			
			finalize();
			
		}
		break;
	case RPC_INITIALIZETRANSIENTMEMBERS__:
		{
			
			initializeTransientMembers();
			
		}
		break;
	case RPC_SENDBASELINESTO__SCENEOBJECT_:
		{
			SceneObject* player = static_cast<SceneObject*>(inv->getObjectParameter());
			
			sendBaselinesTo(player);
			
		}
		break;
	case RPC_UPDATESTATUS__INT_BOOL_:
		{
			int newStatus = inv->getSignedIntParameter();
			bool notifyClient = inv->getBooleanParameter();
			
			updateStatus(newStatus, notifyClient);
			
		}
		break;
	case RPC_SETCUSTOMOBJECTNAME__UNICODESTRING_BOOL_:
		{
			 UnicodeString name; inv->getUnicodeParameter(name);
			bool notifyClient = inv->getBooleanParameter();
			
			setCustomObjectName(name, notifyClient);
			
		}
		break;
	case RPC_SETDATASIZE__FLOAT_BOOL_:
		{
			float dataSize = inv->getFloatParameter();
			bool notifyClient = inv->getBooleanParameter();
			
			setDataSize(dataSize, notifyClient);
			
		}
		break;
	case RPC_SETITEMIDENTIFIER__STRING_BOOL_:
		{
			 String itemName; inv->getAsciiParameter(itemName);
			bool notifyClient = inv->getBooleanParameter();
			
			setItemIdentifier(itemName, notifyClient);
			
		}
		break;
	case RPC_GETSTATUS__:
		{
			
			unsigned int _m_res = getStatus();
			resp->insertInt(_m_res);
		}
		break;
	case RPC_GETDATASIZE__:
		{
			
			float _m_res = getDataSize();
			resp->insertFloat(_m_res);
		}
		break;
	case RPC_GETITEMIDENTIFIER__:
		{
			
			String _m_res = getItemIdentifier();
			resp->insertAscii(_m_res);
		}
		break;
	case RPC_ISINTANGIBLEOBJECT__:
		{
			
			bool _m_res = isIntangibleObject();
			resp->insertBoolean(_m_res);
		}
		break;
	default:
		SceneObjectAdapter::invokeMethod(methid, inv);
	}
}

void IntangibleObjectAdapter::finalize() {
	(static_cast<IntangibleObject*>(stub))->finalize();
}

void IntangibleObjectAdapter::initializeTransientMembers() {
	(static_cast<IntangibleObject*>(stub))->initializeTransientMembers();
}

void IntangibleObjectAdapter::sendBaselinesTo(SceneObject* player) {
	(static_cast<IntangibleObject*>(stub))->sendBaselinesTo(player);
}

void IntangibleObjectAdapter::updateStatus(int newStatus, bool notifyClient) {
	(static_cast<IntangibleObject*>(stub))->updateStatus(newStatus, notifyClient);
}

void IntangibleObjectAdapter::setCustomObjectName(const UnicodeString& name, bool notifyClient) {
	(static_cast<IntangibleObject*>(stub))->setCustomObjectName(name, notifyClient);
}

void IntangibleObjectAdapter::setDataSize(float dataSize, bool notifyClient) {
	(static_cast<IntangibleObject*>(stub))->setDataSize(dataSize, notifyClient);
}

void IntangibleObjectAdapter::setItemIdentifier(const String& itemName, bool notifyClient) {
	(static_cast<IntangibleObject*>(stub))->setItemIdentifier(itemName, notifyClient);
}

unsigned int IntangibleObjectAdapter::getStatus() const {
	return (static_cast<IntangibleObject*>(stub))->getStatus();
}

float IntangibleObjectAdapter::getDataSize() const {
	return (static_cast<IntangibleObject*>(stub))->getDataSize();
}

String IntangibleObjectAdapter::getItemIdentifier() const {
	return (static_cast<IntangibleObject*>(stub))->getItemIdentifier();
}

bool IntangibleObjectAdapter::isIntangibleObject() {
	return (static_cast<IntangibleObject*>(stub))->isIntangibleObject();
}

/*
 *	IntangibleObjectHelper
 */

IntangibleObjectHelper* IntangibleObjectHelper::staticInitializer = IntangibleObjectHelper::instance();

IntangibleObjectHelper::IntangibleObjectHelper() {
	className = "IntangibleObject";

	Core::getObjectBroker()->registerClass(className, this);
}

void IntangibleObjectHelper::finalizeHelper() {
	IntangibleObjectHelper::finalize();
}

DistributedObject* IntangibleObjectHelper::instantiateObject() {
	return new IntangibleObject(DummyConstructorParameter::instance());
}

DistributedObjectServant* IntangibleObjectHelper::instantiateServant() {
	return new IntangibleObjectImplementation();
}

DistributedObjectPOD* IntangibleObjectHelper::instantiatePOD() {
	return new IntangibleObjectPOD();
}

DistributedObjectAdapter* IntangibleObjectHelper::createAdapter(DistributedObjectStub* obj) {
	DistributedObjectAdapter* adapter = new IntangibleObjectAdapter(static_cast<IntangibleObject*>(obj));

	obj->_setClassName(className);
	obj->_setClassHelper(this);

	adapter->setStub(obj);

	return adapter;
}

/*
 *	IntangibleObjectPOD
 */

IntangibleObjectPOD::~IntangibleObjectPOD() {
	finalize();
}

IntangibleObjectPOD::IntangibleObjectPOD(void) {
	_className = "IntangibleObject";
}


void IntangibleObjectPOD::writeJSON(nlohmann::json& j) {
	SceneObjectPOD::writeJSON(j);

	nlohmann::json thisObject = nlohmann::json::object();
	if (status)
		thisObject["status"] = status.value();

	if (datapadSize)
		thisObject["datapadSize"] = datapadSize.value();

	if (itemIdentifier)
		thisObject["itemIdentifier"] = itemIdentifier.value();

	j["IntangibleObject"] = thisObject;
}


void IntangibleObjectPOD::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = IntangibleObjectPOD::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int IntangibleObjectPOD::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = SceneObjectPOD::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;
	if (status) {
	_nameHashCode = 0xca41f7e6; //IntangibleObject.status
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<unsigned int >::toBinaryStream(&status.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (datapadSize) {
	_nameHashCode = 0xb5fd3566; //IntangibleObject.datapadSize
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&datapadSize.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (itemIdentifier) {
	_nameHashCode = 0xc8d420ff; //IntangibleObject.itemIdentifier
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<String >::toBinaryStream(&itemIdentifier.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}


	return _count;
}

bool IntangibleObjectPOD::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (SceneObjectPOD::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	case 0xca41f7e6: //IntangibleObject.status
		{
			unsigned int _mnstatus;
			TypeInfo<unsigned int >::parseFromBinaryStream(&_mnstatus, stream);
			status = std::move(_mnstatus);
		}
		return true;

	case 0xb5fd3566: //IntangibleObject.datapadSize
		{
			float _mndatapadSize;
			TypeInfo<float >::parseFromBinaryStream(&_mndatapadSize, stream);
			datapadSize = std::move(_mndatapadSize);
		}
		return true;

	case 0xc8d420ff: //IntangibleObject.itemIdentifier
		{
			String _mnitemIdentifier;
			TypeInfo<String >::parseFromBinaryStream(&_mnitemIdentifier, stream);
			itemIdentifier = std::move(_mnitemIdentifier);
		}
		return true;

	}

	return false;
}

void IntangibleObjectPOD::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(IntangibleObjectPOD::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

}

void IntangibleObjectPOD::writeObjectCompact(ObjectOutputStream* stream) {
	SceneObjectPOD::writeObjectCompact(stream);

	TypeInfo<unsigned int >::toBinaryStream(&status.value(), stream);

	TypeInfo<float >::toBinaryStream(&datapadSize.value(), stream);

	TypeInfo<String >::toBinaryStream(&itemIdentifier.value(), stream);


}

