/*
 *	autogen/server/zone/objects/intangible/ShipControlDevice.cpp generated by engine3 IDL compiler 0.70
 */

#include "ShipControlDevice.h"

#include "server/zone/objects/creature/CreatureObject.h"

#include "server/zone/packets/object/ObjectMenuResponse.h"

#include "server/zone/objects/scene/SceneObject.h"

#include "server/zone/objects/ship/ShipObject.h"

#include "server/zone/packets/scene/AttributeListMessage.h"

/*
 *	ShipControlDeviceStub
 */

enum {RPC_LAUNCHSHIP__CREATUREOBJECT_STRING_VECTOR3_ = 294561104,RPC_HANDLEOBJECTMENUSELECT__CREATUREOBJECT_BYTE_,RPC_CANBETRADEDTO__CREATUREOBJECT_CREATUREOBJECT_INT_,RPC_SETSTOREDLOCATIONDATA__CREATUREOBJECT_,RPC_CANBEDESTROYED__CREATUREOBJECT_,RPC_DESTROYOBJECTFROMDATABASE__BOOL_,RPC_ISSHIPLAUNCHED__,RPC_ISSHIPCONTROLDEVICE__,RPC_GETPARKINGLOCATION__,RPC_GETSTOREDZONENAME__,RPC_GETSHIPTYPE__,RPC_GETTOTALSKILLSREQUIRED__,RPC_GETSKILLREQUIRED__INT_,RPC_SETPARKINGLOCATION__STRING_,RPC_ADDSKILLREQUIRED__STRING_};

ShipControlDevice::ShipControlDevice() : ControlDevice(DummyConstructorParameter::instance()) {
	ShipControlDeviceImplementation* _implementation = new ShipControlDeviceImplementation();
	_impl = _implementation;
	_impl->_setStub(this);
	_setClassName("ShipControlDevice");
}

ShipControlDevice::ShipControlDevice(DummyConstructorParameter* param) : ControlDevice(param) {
	_setClassName("ShipControlDevice");
}

ShipControlDevice::~ShipControlDevice() {
}



ShipObject* ShipControlDevice::launchShip(CreatureObject* player, const String& zoneName, const Vector3& position) {
	ShipControlDeviceImplementation* _implementation = static_cast<ShipControlDeviceImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_LAUNCHSHIP__CREATUREOBJECT_STRING_VECTOR3_);
		method.addObjectParameter(player);
		method.addAsciiParameter(zoneName);
		method.addDereferencedSerializableParameter(position);

		return static_cast<ShipObject*>(method.executeWithObjectReturn());
	} else {
		assert(this->isLockedByCurrentThread());
		return _implementation->launchShip(player, zoneName, position);
	}
}

int ShipControlDevice::handleObjectMenuSelect(CreatureObject* player, byte selectedID) {
	ShipControlDeviceImplementation* _implementation = static_cast<ShipControlDeviceImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_HANDLEOBJECTMENUSELECT__CREATUREOBJECT_BYTE_);
		method.addObjectParameter(player);
		method.addByteParameter(selectedID);

		return method.executeWithSignedIntReturn();
	} else {
		assert(this->isLockedByCurrentThread());
		assert((player == NULL) || player->isLockedByCurrentThread());
		return _implementation->handleObjectMenuSelect(player, selectedID);
	}
}

void ShipControlDevice::fillObjectMenuResponse(ObjectMenuResponse* menuResponse, CreatureObject* player) {
	ShipControlDeviceImplementation* _implementation = static_cast<ShipControlDeviceImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->fillObjectMenuResponse(menuResponse, player);
	}
}

void ShipControlDevice::fillAttributeList(AttributeListMessage* alm, CreatureObject* object) {
	ShipControlDeviceImplementation* _implementation = static_cast<ShipControlDeviceImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->fillAttributeList(alm, object);
	}
}

bool ShipControlDevice::canBeTradedTo(CreatureObject* player, CreatureObject* receiver, int numberInTrade) {
	ShipControlDeviceImplementation* _implementation = static_cast<ShipControlDeviceImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_CANBETRADEDTO__CREATUREOBJECT_CREATUREOBJECT_INT_);
		method.addObjectParameter(player);
		method.addObjectParameter(receiver);
		method.addSignedIntParameter(numberInTrade);

		return method.executeWithBooleanReturn();
	} else {
		return _implementation->canBeTradedTo(player, receiver, numberInTrade);
	}
}

Vector3 ShipControlDevice::getStoredPosition(bool randomPosition) {
	ShipControlDeviceImplementation* _implementation = static_cast<ShipControlDeviceImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		return _implementation->getStoredPosition(randomPosition);
	}
}

void ShipControlDevice::setStoredLocationData(CreatureObject* player) {
	ShipControlDeviceImplementation* _implementation = static_cast<ShipControlDeviceImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_SETSTOREDLOCATIONDATA__CREATUREOBJECT_);
		method.addObjectParameter(player);

		method.executeWithVoidReturn();
	} else {
		assert((player == NULL) || player->isLockedByCurrentThread());
		_implementation->setStoredLocationData(player);
	}
}

int ShipControlDevice::canBeDestroyed(CreatureObject* player) {
	ShipControlDeviceImplementation* _implementation = static_cast<ShipControlDeviceImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_CANBEDESTROYED__CREATUREOBJECT_);
		method.addObjectParameter(player);

		return method.executeWithSignedIntReturn();
	} else {
		return _implementation->canBeDestroyed(player);
	}
}

void ShipControlDevice::destroyObjectFromDatabase(bool destroyContainedObjects) {
	ShipControlDeviceImplementation* _implementation = static_cast<ShipControlDeviceImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_DESTROYOBJECTFROMDATABASE__BOOL_);
		method.addBooleanParameter(destroyContainedObjects);

		method.executeWithVoidReturn();
	} else {
		assert(this->isLockedByCurrentThread());
		_implementation->destroyObjectFromDatabase(destroyContainedObjects);
	}
}

bool ShipControlDevice::isShipLaunched() {
	ShipControlDeviceImplementation* _implementation = static_cast<ShipControlDeviceImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_ISSHIPLAUNCHED__);

		return method.executeWithBooleanReturn();
	} else {
		return _implementation->isShipLaunched();
	}
}

bool ShipControlDevice::isShipControlDevice() {
	ShipControlDeviceImplementation* _implementation = static_cast<ShipControlDeviceImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_ISSHIPCONTROLDEVICE__);

		return method.executeWithBooleanReturn();
	} else {
		return _implementation->isShipControlDevice();
	}
}

String ShipControlDevice::getParkingLocation() {
	ShipControlDeviceImplementation* _implementation = static_cast<ShipControlDeviceImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETPARKINGLOCATION__);

		String _return_getParkingLocation;
		method.executeWithAsciiReturn(_return_getParkingLocation);
		return _return_getParkingLocation;
	} else {
		return _implementation->getParkingLocation();
	}
}

String ShipControlDevice::getStoredZoneName() {
	ShipControlDeviceImplementation* _implementation = static_cast<ShipControlDeviceImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETSTOREDZONENAME__);

		String _return_getStoredZoneName;
		method.executeWithAsciiReturn(_return_getStoredZoneName);
		return _return_getStoredZoneName;
	} else {
		return _implementation->getStoredZoneName();
	}
}

int ShipControlDevice::getShipType() {
	ShipControlDeviceImplementation* _implementation = static_cast<ShipControlDeviceImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETSHIPTYPE__);

		return method.executeWithSignedIntReturn();
	} else {
		return _implementation->getShipType();
	}
}

int ShipControlDevice::getTotalSkillsRequired() {
	ShipControlDeviceImplementation* _implementation = static_cast<ShipControlDeviceImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETTOTALSKILLSREQUIRED__);

		return method.executeWithSignedIntReturn();
	} else {
		return _implementation->getTotalSkillsRequired();
	}
}

String ShipControlDevice::getSkillRequired(int index) {
	ShipControlDeviceImplementation* _implementation = static_cast<ShipControlDeviceImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETSKILLREQUIRED__INT_);
		method.addSignedIntParameter(index);

		String _return_getSkillRequired;
		method.executeWithAsciiReturn(_return_getSkillRequired);
		return _return_getSkillRequired;
	} else {
		return _implementation->getSkillRequired(index);
	}
}

void ShipControlDevice::setShipType(int type) {
	ShipControlDeviceImplementation* _implementation = static_cast<ShipControlDeviceImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		assert(this->isLockedByCurrentThread());
		_implementation->setShipType(type);
	}
}

void ShipControlDevice::setParkingLocation(const String& cityName) {
	ShipControlDeviceImplementation* _implementation = static_cast<ShipControlDeviceImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_SETPARKINGLOCATION__STRING_);
		method.addAsciiParameter(cityName);

		method.executeWithVoidReturn();
	} else {
		assert(this->isLockedByCurrentThread());
		_implementation->setParkingLocation(cityName);
	}
}

void ShipControlDevice::addSkillRequired(String& skill) {
	ShipControlDeviceImplementation* _implementation = static_cast<ShipControlDeviceImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_ADDSKILLREQUIRED__STRING_);
		method.addAsciiParameter(skill);

		method.executeWithVoidReturn();
	} else {
		_implementation->addSkillRequired(skill);
	}
}

DistributedObjectServant* ShipControlDevice::_getImplementation() {

	 if (!_updated) _updated = true;
	return _impl;
}

DistributedObjectServant* ShipControlDevice::_getImplementationForRead() const {
	return _impl;
}

void ShipControlDevice::_setImplementation(DistributedObjectServant* servant) {
	_impl = servant;
}

/*
 *	ShipControlDeviceImplementation
 */

ShipControlDeviceImplementation::ShipControlDeviceImplementation(DummyConstructorParameter* param) : ControlDeviceImplementation(param) {
	_initializeImplementation();
}


ShipControlDeviceImplementation::~ShipControlDeviceImplementation() {
}


void ShipControlDeviceImplementation::finalize() {
}

void ShipControlDeviceImplementation::_initializeImplementation() {
	_setClassHelper(ShipControlDeviceHelper::instance());

	_this = NULL;

	_serializationHelperMethod();
}

void ShipControlDeviceImplementation::_setStub(DistributedObjectStub* stub) {
	_this = static_cast<ShipControlDevice*>(stub);
	ControlDeviceImplementation::_setStub(stub);
}

DistributedObjectStub* ShipControlDeviceImplementation::_getStub() {
	return _this.get();
}

ShipControlDeviceImplementation::operator const ShipControlDevice*() {
	return _this.get();
}

void ShipControlDeviceImplementation::lock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->lock(doLock);
}

void ShipControlDeviceImplementation::lock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->lock(obj);
}

void ShipControlDeviceImplementation::rlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->rlock(doLock);
}

void ShipControlDeviceImplementation::wlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->wlock(doLock);
}

void ShipControlDeviceImplementation::wlock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->wlock(obj);
}

void ShipControlDeviceImplementation::unlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->unlock(doLock);
}

void ShipControlDeviceImplementation::runlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->runlock(doLock);
}

void ShipControlDeviceImplementation::_serializationHelperMethod() {
	ControlDeviceImplementation::_serializationHelperMethod();

	_setClassName("ShipControlDevice");

}

void ShipControlDeviceImplementation::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(ShipControlDeviceImplementation::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

	initializeTransientMembers();
}

bool ShipControlDeviceImplementation::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (ControlDeviceImplementation::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	case 0x3d340423: //ShipControlDevice.shipType
		TypeInfo<int >::parseFromBinaryStream(&shipType, stream);
		return true;

	case 0xfb4db8b8: //ShipControlDevice.parkingLocation
		TypeInfo<String >::parseFromBinaryStream(&parkingLocation, stream);
		return true;

	case 0x408ed1dc: //ShipControlDevice.storedZoneName
		TypeInfo<String >::parseFromBinaryStream(&storedZoneName, stream);
		return true;

	case 0x87a4424b: //ShipControlDevice.storedPosition
		TypeInfo<Vector3 >::parseFromBinaryStream(&storedPosition, stream);
		return true;

	case 0xe9e02705: //ShipControlDevice.skillsRequired
		TypeInfo<Vector<String> >::parseFromBinaryStream(&skillsRequired, stream);
		return true;

	}

	return false;
}

void ShipControlDeviceImplementation::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = ShipControlDeviceImplementation::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int ShipControlDeviceImplementation::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = ControlDeviceImplementation::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;
	_nameHashCode = 0x3d340423; //ShipControlDevice.shipType
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<int >::toBinaryStream(&shipType, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0xfb4db8b8; //ShipControlDevice.parkingLocation
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<String >::toBinaryStream(&parkingLocation, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0x408ed1dc; //ShipControlDevice.storedZoneName
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<String >::toBinaryStream(&storedZoneName, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0x87a4424b; //ShipControlDevice.storedPosition
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<Vector3 >::toBinaryStream(&storedPosition, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0xe9e02705; //ShipControlDevice.skillsRequired
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<Vector<String> >::toBinaryStream(&skillsRequired, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;


	return _count;
}

void ShipControlDeviceImplementation::writeJSON(nlohmann::json& j) {
	ControlDeviceImplementation::writeJSON(j);

	nlohmann::json thisObject = nlohmann::json::object();
	thisObject["shipType"] = shipType;

	thisObject["parkingLocation"] = parkingLocation;

	thisObject["storedZoneName"] = storedZoneName;

	thisObject["storedPosition"] = storedPosition;

	thisObject["skillsRequired"] = skillsRequired;

	j["ShipControlDevice"] = thisObject;
}

ShipControlDeviceImplementation::ShipControlDeviceImplementation() {
	_initializeImplementation();
	// server/zone/objects/intangible/ShipControlDevice.idl():  		Logger.setLoggingName("ShipControlDevice");
	Logger::setLoggingName("ShipControlDevice");
	// server/zone/objects/intangible/ShipControlDevice.idl():  		shipType = 0;
	shipType = 0;
}

bool ShipControlDeviceImplementation::isShipControlDevice() {
	// server/zone/objects/intangible/ShipControlDevice.idl():  		return true;
	return true;
}

String ShipControlDeviceImplementation::getParkingLocation() {
	// server/zone/objects/intangible/ShipControlDevice.idl():  		return parkingLocation;
	return parkingLocation;
}

String ShipControlDeviceImplementation::getStoredZoneName() {
	// server/zone/objects/intangible/ShipControlDevice.idl():  		return storedZoneName;
	return storedZoneName;
}

int ShipControlDeviceImplementation::getShipType() {
	// server/zone/objects/intangible/ShipControlDevice.idl():  		return shipType;
	return shipType;
}

int ShipControlDeviceImplementation::getTotalSkillsRequired() {
	// server/zone/objects/intangible/ShipControlDevice.idl():  		return skillsRequired.size();
	return (&skillsRequired)->size();
}

String ShipControlDeviceImplementation::getSkillRequired(int index) {
	// server/zone/objects/intangible/ShipControlDevice.idl():  		return skillsRequired.get(index);
	return (&skillsRequired)->get(index);
}

void ShipControlDeviceImplementation::setShipType(int type) {
	// server/zone/objects/intangible/ShipControlDevice.idl():  		shipType = type;
	shipType = type;
}

void ShipControlDeviceImplementation::setParkingLocation(const String& cityName) {
	// server/zone/objects/intangible/ShipControlDevice.idl():  		parkingLocation = cityName;
	parkingLocation = cityName;
}

void ShipControlDeviceImplementation::addSkillRequired(String& skill) {
	// server/zone/objects/intangible/ShipControlDevice.idl():  		skillsRequired.add(skill);
	(&skillsRequired)->add(skill);
}

/*
 *	ShipControlDeviceAdapter
 */


#include "engine/orb/messages/InvokeMethodMessage.h"


ShipControlDeviceAdapter::ShipControlDeviceAdapter(ShipControlDevice* obj) : ControlDeviceAdapter(obj) {
}

void ShipControlDeviceAdapter::invokeMethod(uint32 methid, DistributedMethod* inv) {
	DOBMessage* resp = inv->getInvocationMessage();

	switch (methid) {
	case RPC_LAUNCHSHIP__CREATUREOBJECT_STRING_VECTOR3_:
		{
			CreatureObject* player = static_cast<CreatureObject*>(inv->getObjectParameter());
			 String zoneName; inv->getAsciiParameter(zoneName);
			 Vector3 position = inv->getDereferencedSerializableParameter<Vector3 >();
			
			DistributedObject* _m_res = launchShip(player, zoneName, position);
			resp->insertLong(_m_res == NULL ? 0 : _m_res->_getObjectID());
		}
		break;
	case RPC_HANDLEOBJECTMENUSELECT__CREATUREOBJECT_BYTE_:
		{
			CreatureObject* player = static_cast<CreatureObject*>(inv->getObjectParameter());
			byte selectedID = inv->getByteParameter();
			
			int _m_res = handleObjectMenuSelect(player, selectedID);
			resp->insertSignedInt(_m_res);
		}
		break;
	case RPC_CANBETRADEDTO__CREATUREOBJECT_CREATUREOBJECT_INT_:
		{
			CreatureObject* player = static_cast<CreatureObject*>(inv->getObjectParameter());
			CreatureObject* receiver = static_cast<CreatureObject*>(inv->getObjectParameter());
			int numberInTrade = inv->getSignedIntParameter();
			
			bool _m_res = canBeTradedTo(player, receiver, numberInTrade);
			resp->insertBoolean(_m_res);
		}
		break;
	case RPC_SETSTOREDLOCATIONDATA__CREATUREOBJECT_:
		{
			CreatureObject* player = static_cast<CreatureObject*>(inv->getObjectParameter());
			
			setStoredLocationData(player);
			
		}
		break;
	case RPC_CANBEDESTROYED__CREATUREOBJECT_:
		{
			CreatureObject* player = static_cast<CreatureObject*>(inv->getObjectParameter());
			
			int _m_res = canBeDestroyed(player);
			resp->insertSignedInt(_m_res);
		}
		break;
	case RPC_DESTROYOBJECTFROMDATABASE__BOOL_:
		{
			bool destroyContainedObjects = inv->getBooleanParameter();
			
			destroyObjectFromDatabase(destroyContainedObjects);
			
		}
		break;
	case RPC_ISSHIPLAUNCHED__:
		{
			
			bool _m_res = isShipLaunched();
			resp->insertBoolean(_m_res);
		}
		break;
	case RPC_ISSHIPCONTROLDEVICE__:
		{
			
			bool _m_res = isShipControlDevice();
			resp->insertBoolean(_m_res);
		}
		break;
	case RPC_GETPARKINGLOCATION__:
		{
			
			String _m_res = getParkingLocation();
			resp->insertAscii(_m_res);
		}
		break;
	case RPC_GETSTOREDZONENAME__:
		{
			
			String _m_res = getStoredZoneName();
			resp->insertAscii(_m_res);
		}
		break;
	case RPC_GETSHIPTYPE__:
		{
			
			int _m_res = getShipType();
			resp->insertSignedInt(_m_res);
		}
		break;
	case RPC_GETTOTALSKILLSREQUIRED__:
		{
			
			int _m_res = getTotalSkillsRequired();
			resp->insertSignedInt(_m_res);
		}
		break;
	case RPC_GETSKILLREQUIRED__INT_:
		{
			int index = inv->getSignedIntParameter();
			
			String _m_res = getSkillRequired(index);
			resp->insertAscii(_m_res);
		}
		break;
	case RPC_SETPARKINGLOCATION__STRING_:
		{
			 String cityName; inv->getAsciiParameter(cityName);
			
			setParkingLocation(cityName);
			
		}
		break;
	case RPC_ADDSKILLREQUIRED__STRING_:
		{
			String skill; inv->getAsciiParameter(skill);
			
			addSkillRequired(skill);
			
		}
		break;
	default:
		ControlDeviceAdapter::invokeMethod(methid, inv);
	}
}

ShipObject* ShipControlDeviceAdapter::launchShip(CreatureObject* player, const String& zoneName, const Vector3& position) {
	return (static_cast<ShipControlDevice*>(stub))->launchShip(player, zoneName, position);
}

int ShipControlDeviceAdapter::handleObjectMenuSelect(CreatureObject* player, byte selectedID) {
	return (static_cast<ShipControlDevice*>(stub))->handleObjectMenuSelect(player, selectedID);
}

bool ShipControlDeviceAdapter::canBeTradedTo(CreatureObject* player, CreatureObject* receiver, int numberInTrade) {
	return (static_cast<ShipControlDevice*>(stub))->canBeTradedTo(player, receiver, numberInTrade);
}

void ShipControlDeviceAdapter::setStoredLocationData(CreatureObject* player) {
	(static_cast<ShipControlDevice*>(stub))->setStoredLocationData(player);
}

int ShipControlDeviceAdapter::canBeDestroyed(CreatureObject* player) {
	return (static_cast<ShipControlDevice*>(stub))->canBeDestroyed(player);
}

void ShipControlDeviceAdapter::destroyObjectFromDatabase(bool destroyContainedObjects) {
	(static_cast<ShipControlDevice*>(stub))->destroyObjectFromDatabase(destroyContainedObjects);
}

bool ShipControlDeviceAdapter::isShipLaunched() {
	return (static_cast<ShipControlDevice*>(stub))->isShipLaunched();
}

bool ShipControlDeviceAdapter::isShipControlDevice() {
	return (static_cast<ShipControlDevice*>(stub))->isShipControlDevice();
}

String ShipControlDeviceAdapter::getParkingLocation() {
	return (static_cast<ShipControlDevice*>(stub))->getParkingLocation();
}

String ShipControlDeviceAdapter::getStoredZoneName() {
	return (static_cast<ShipControlDevice*>(stub))->getStoredZoneName();
}

int ShipControlDeviceAdapter::getShipType() {
	return (static_cast<ShipControlDevice*>(stub))->getShipType();
}

int ShipControlDeviceAdapter::getTotalSkillsRequired() {
	return (static_cast<ShipControlDevice*>(stub))->getTotalSkillsRequired();
}

String ShipControlDeviceAdapter::getSkillRequired(int index) {
	return (static_cast<ShipControlDevice*>(stub))->getSkillRequired(index);
}

void ShipControlDeviceAdapter::setParkingLocation(const String& cityName) {
	(static_cast<ShipControlDevice*>(stub))->setParkingLocation(cityName);
}

void ShipControlDeviceAdapter::addSkillRequired(String& skill) {
	(static_cast<ShipControlDevice*>(stub))->addSkillRequired(skill);
}

/*
 *	ShipControlDeviceHelper
 */

ShipControlDeviceHelper* ShipControlDeviceHelper::staticInitializer = ShipControlDeviceHelper::instance();

ShipControlDeviceHelper::ShipControlDeviceHelper() {
	className = "ShipControlDevice";

	Core::getObjectBroker()->registerClass(className, this);
}

void ShipControlDeviceHelper::finalizeHelper() {
	ShipControlDeviceHelper::finalize();
}

DistributedObject* ShipControlDeviceHelper::instantiateObject() {
	return new ShipControlDevice(DummyConstructorParameter::instance());
}

DistributedObjectServant* ShipControlDeviceHelper::instantiateServant() {
	return new ShipControlDeviceImplementation();
}

DistributedObjectPOD* ShipControlDeviceHelper::instantiatePOD() {
	return new ShipControlDevicePOD();
}

DistributedObjectAdapter* ShipControlDeviceHelper::createAdapter(DistributedObjectStub* obj) {
	DistributedObjectAdapter* adapter = new ShipControlDeviceAdapter(static_cast<ShipControlDevice*>(obj));

	obj->_setClassName(className);
	obj->_setClassHelper(this);

	adapter->setStub(obj);

	return adapter;
}

/*
 *	ShipControlDevicePOD
 */

ShipControlDevicePOD::~ShipControlDevicePOD() {
	finalize();
}

ShipControlDevicePOD::ShipControlDevicePOD(void) {
	_className = "ShipControlDevice";
}


void ShipControlDevicePOD::writeJSON(nlohmann::json& j) {
	ControlDevicePOD::writeJSON(j);

	nlohmann::json thisObject = nlohmann::json::object();
	if (shipType)
		thisObject["shipType"] = shipType.value();

	if (parkingLocation)
		thisObject["parkingLocation"] = parkingLocation.value();

	if (storedZoneName)
		thisObject["storedZoneName"] = storedZoneName.value();

	if (storedPosition)
		thisObject["storedPosition"] = storedPosition.value();

	if (skillsRequired)
		thisObject["skillsRequired"] = skillsRequired.value();

	j["ShipControlDevice"] = thisObject;
}


void ShipControlDevicePOD::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = ShipControlDevicePOD::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int ShipControlDevicePOD::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = ControlDevicePOD::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;
	if (shipType) {
	_nameHashCode = 0x3d340423; //ShipControlDevice.shipType
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<int >::toBinaryStream(&shipType.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (parkingLocation) {
	_nameHashCode = 0xfb4db8b8; //ShipControlDevice.parkingLocation
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<String >::toBinaryStream(&parkingLocation.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (storedZoneName) {
	_nameHashCode = 0x408ed1dc; //ShipControlDevice.storedZoneName
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<String >::toBinaryStream(&storedZoneName.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (storedPosition) {
	_nameHashCode = 0x87a4424b; //ShipControlDevice.storedPosition
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<Vector3 >::toBinaryStream(&storedPosition.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (skillsRequired) {
	_nameHashCode = 0xe9e02705; //ShipControlDevice.skillsRequired
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<Vector<String> >::toBinaryStream(&skillsRequired.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}


	return _count;
}

bool ShipControlDevicePOD::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (ControlDevicePOD::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	case 0x3d340423: //ShipControlDevice.shipType
		{
			int _mnshipType;
			TypeInfo<int >::parseFromBinaryStream(&_mnshipType, stream);
			shipType = std::move(_mnshipType);
		}
		return true;

	case 0xfb4db8b8: //ShipControlDevice.parkingLocation
		{
			String _mnparkingLocation;
			TypeInfo<String >::parseFromBinaryStream(&_mnparkingLocation, stream);
			parkingLocation = std::move(_mnparkingLocation);
		}
		return true;

	case 0x408ed1dc: //ShipControlDevice.storedZoneName
		{
			String _mnstoredZoneName;
			TypeInfo<String >::parseFromBinaryStream(&_mnstoredZoneName, stream);
			storedZoneName = std::move(_mnstoredZoneName);
		}
		return true;

	case 0x87a4424b: //ShipControlDevice.storedPosition
		{
			Vector3 _mnstoredPosition;
			TypeInfo<Vector3 >::parseFromBinaryStream(&_mnstoredPosition, stream);
			storedPosition = std::move(_mnstoredPosition);
		}
		return true;

	case 0xe9e02705: //ShipControlDevice.skillsRequired
		{
			Vector<String> _mnskillsRequired;
			TypeInfo<Vector<String> >::parseFromBinaryStream(&_mnskillsRequired, stream);
			skillsRequired = std::move(_mnskillsRequired);
		}
		return true;

	}

	return false;
}

void ShipControlDevicePOD::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(ShipControlDevicePOD::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

}

void ShipControlDevicePOD::writeObjectCompact(ObjectOutputStream* stream) {
	ControlDevicePOD::writeObjectCompact(stream);

	TypeInfo<int >::toBinaryStream(&shipType.value(), stream);

	TypeInfo<String >::toBinaryStream(&parkingLocation.value(), stream);

	TypeInfo<String >::toBinaryStream(&storedZoneName.value(), stream);

	TypeInfo<Vector3 >::toBinaryStream(&storedPosition.value(), stream);

	TypeInfo<Vector<String> >::toBinaryStream(&skillsRequired.value(), stream);


}

