/*
 *	autogen/server/zone/objects/intangible/StructureControlDevice.cpp generated by engine3 IDL compiler 0.70
 */

#include "StructureControlDevice.h"

#include "server/zone/objects/creature/CreatureObject.h"

#include "server/zone/objects/structure/StructureObject.h"

#include "server/zone/packets/object/ObjectMenuResponse.h"

#include "server/zone/packets/scene/AttributeListMessage.h"

/*
 *	StructureControlDeviceStub
 */

enum {RPC_HANDLEOBJECTMENUSELECT__CREATUREOBJECT_BYTE_,RPC_PLACESTRUCTURE__CREATUREOBJECT_FLOAT_FLOAT_INT_,RPC_NOTIFYSTRUCTUREPLACED__CREATUREOBJECT_STRUCTUREOBJECT_,RPC_ISSTRUCTURECONTROLDEVICE__};

StructureControlDevice::StructureControlDevice() : ControlDevice(DummyConstructorParameter::instance()) {
	StructureControlDeviceImplementation* _implementation = new StructureControlDeviceImplementation();
	_impl = _implementation;
	_impl->_setStub(this);
	_setClassName("StructureControlDevice");
}

StructureControlDevice::StructureControlDevice(DummyConstructorParameter* param) : ControlDevice(param) {
	_setClassName("StructureControlDevice");
}

StructureControlDevice::~StructureControlDevice() {
}



void StructureControlDevice::fillObjectMenuResponse(ObjectMenuResponse* menuResponse, CreatureObject* player) {
	StructureControlDeviceImplementation* _implementation = static_cast<StructureControlDeviceImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == nullptr)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->fillObjectMenuResponse(menuResponse, player);
	}
}

int StructureControlDevice::handleObjectMenuSelect(CreatureObject* player, byte selectedID) {
	StructureControlDeviceImplementation* _implementation = static_cast<StructureControlDeviceImplementation*>(_getImplementation());
	if (unlikely(_implementation == nullptr)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_HANDLEOBJECTMENUSELECT__CREATUREOBJECT_BYTE_);
		method.addObjectParameter(player);
		method.addByteParameter(selectedID);

		return method.executeWithSignedIntReturn();
	} else {
		return _implementation->handleObjectMenuSelect(player, selectedID);
	}
}

void StructureControlDevice::placeStructureMode(CreatureObject* player, StructureObject* structure) {
	StructureControlDeviceImplementation* _implementation = static_cast<StructureControlDeviceImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == nullptr)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->placeStructureMode(player, structure);
	}
}

int StructureControlDevice::placeStructure(CreatureObject* creature, float x, float y, int angle) {
	StructureControlDeviceImplementation* _implementation = static_cast<StructureControlDeviceImplementation*>(_getImplementation());
	if (unlikely(_implementation == nullptr)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_PLACESTRUCTURE__CREATUREOBJECT_FLOAT_FLOAT_INT_);
		method.addObjectParameter(creature);
		method.addFloatParameter(x);
		method.addFloatParameter(y);
		method.addSignedIntParameter(angle);

		return method.executeWithSignedIntReturn();
	} else {
		return _implementation->placeStructure(creature, x, y, angle);
	}
}

int StructureControlDevice::notifyStructurePlaced(CreatureObject* creature, StructureObject* structure) {
	StructureControlDeviceImplementation* _implementation = static_cast<StructureControlDeviceImplementation*>(_getImplementation());
	if (unlikely(_implementation == nullptr)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_NOTIFYSTRUCTUREPLACED__CREATUREOBJECT_STRUCTUREOBJECT_);
		method.addObjectParameter(creature);
		method.addObjectParameter(structure);

		return method.executeWithSignedIntReturn();
	} else {
		return _implementation->notifyStructurePlaced(creature, structure);
	}
}

void StructureControlDevice::fillAttributeList(AttributeListMessage* msg, CreatureObject* object) {
	StructureControlDeviceImplementation* _implementation = static_cast<StructureControlDeviceImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == nullptr)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->fillAttributeList(msg, object);
	}
}

bool StructureControlDevice::isStructureControlDevice() {
	StructureControlDeviceImplementation* _implementation = static_cast<StructureControlDeviceImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == nullptr)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_ISSTRUCTURECONTROLDEVICE__);

		return method.executeWithBooleanReturn();
	} else {
		return _implementation->isStructureControlDevice();
	}
}

DistributedObjectServant* StructureControlDevice::_getImplementation() {

	 if (!_updated) _updated = true;
	return _impl;
}

DistributedObjectServant* StructureControlDevice::_getImplementationForRead() const {
	return _impl;
}

void StructureControlDevice::_setImplementation(DistributedObjectServant* servant) {
	_impl = servant;
}

/*
 *	StructureControlDeviceImplementation
 */

StructureControlDeviceImplementation::StructureControlDeviceImplementation(DummyConstructorParameter* param) : ControlDeviceImplementation(param) {
	_initializeImplementation();
}


StructureControlDeviceImplementation::~StructureControlDeviceImplementation() {
}


void StructureControlDeviceImplementation::finalize() {
}

void StructureControlDeviceImplementation::_initializeImplementation() {
	_setClassHelper(StructureControlDeviceHelper::instance());

	_this = nullptr;

	_serializationHelperMethod();
}

void StructureControlDeviceImplementation::_setStub(DistributedObjectStub* stub) {
	_this = static_cast<StructureControlDevice*>(stub);
	ControlDeviceImplementation::_setStub(stub);
}

DistributedObjectStub* StructureControlDeviceImplementation::_getStub() {
	return _this.get();
}

StructureControlDeviceImplementation::operator const StructureControlDevice*() {
	return _this.get();
}

void StructureControlDeviceImplementation::lock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->lock(doLock);
}

void StructureControlDeviceImplementation::lock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->lock(obj);
}

void StructureControlDeviceImplementation::rlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->rlock(doLock);
}

void StructureControlDeviceImplementation::wlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->wlock(doLock);
}

void StructureControlDeviceImplementation::wlock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->wlock(obj);
}

void StructureControlDeviceImplementation::unlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->unlock(doLock);
}

void StructureControlDeviceImplementation::runlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->runlock(doLock);
}

void StructureControlDeviceImplementation::_serializationHelperMethod() {
	ControlDeviceImplementation::_serializationHelperMethod();

	_setClassName("StructureControlDevice");

}

void StructureControlDeviceImplementation::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(StructureControlDeviceImplementation::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

	initializeTransientMembers();
}

bool StructureControlDeviceImplementation::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (ControlDeviceImplementation::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	}

	return false;
}

void StructureControlDeviceImplementation::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = StructureControlDeviceImplementation::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int StructureControlDeviceImplementation::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = ControlDeviceImplementation::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;

	return _count;
}

StructureControlDeviceImplementation::StructureControlDeviceImplementation() {
	_initializeImplementation();
	// server/zone/objects/intangible/StructureControlDevice.idl():  		Logger.setLoggingName("StructureControlDevice");
	Logger::setLoggingName("StructureControlDevice");
	// server/zone/objects/intangible/StructureControlDevice.idl():  		Logger.setLogging(false);
	Logger::setLogging(false);
	// server/zone/objects/intangible/StructureControlDevice.idl():  		Logger.setGlobalLogging(true);
	Logger::setGlobalLogging(true);
}

bool StructureControlDeviceImplementation::isStructureControlDevice() {
	// server/zone/objects/intangible/StructureControlDevice.idl():  		return true;
	return true;
}

/*
 *	StructureControlDeviceAdapter
 */


#include "engine/orb/messages/InvokeMethodMessage.h"


StructureControlDeviceAdapter::StructureControlDeviceAdapter(StructureControlDevice* obj) : ControlDeviceAdapter(obj) {
}

void StructureControlDeviceAdapter::invokeMethod(uint32 methid, DistributedMethod* inv) {
	DOBMessage* resp = inv->getInvocationMessage();

	switch (methid) {
	case RPC_HANDLEOBJECTMENUSELECT__CREATUREOBJECT_BYTE_:
		{
			CreatureObject* player = static_cast<CreatureObject*>(inv->getObjectParameter());
			byte selectedID = inv->getByteParameter();
			
			int _m_res = handleObjectMenuSelect(player, selectedID);
			resp->insertSignedInt(_m_res);
		}
		break;
	case RPC_PLACESTRUCTURE__CREATUREOBJECT_FLOAT_FLOAT_INT_:
		{
			CreatureObject* creature = static_cast<CreatureObject*>(inv->getObjectParameter());
			float x = inv->getFloatParameter();
			float y = inv->getFloatParameter();
			int angle = inv->getSignedIntParameter();
			
			int _m_res = placeStructure(creature, x, y, angle);
			resp->insertSignedInt(_m_res);
		}
		break;
	case RPC_NOTIFYSTRUCTUREPLACED__CREATUREOBJECT_STRUCTUREOBJECT_:
		{
			CreatureObject* creature = static_cast<CreatureObject*>(inv->getObjectParameter());
			StructureObject* structure = static_cast<StructureObject*>(inv->getObjectParameter());
			
			int _m_res = notifyStructurePlaced(creature, structure);
			resp->insertSignedInt(_m_res);
		}
		break;
	case RPC_ISSTRUCTURECONTROLDEVICE__:
		{
			
			bool _m_res = isStructureControlDevice();
			resp->insertBoolean(_m_res);
		}
		break;
	default:
		ControlDeviceAdapter::invokeMethod(methid, inv);
	}
}

int StructureControlDeviceAdapter::handleObjectMenuSelect(CreatureObject* player, byte selectedID) {
	return (static_cast<StructureControlDevice*>(stub))->handleObjectMenuSelect(player, selectedID);
}

int StructureControlDeviceAdapter::placeStructure(CreatureObject* creature, float x, float y, int angle) {
	return (static_cast<StructureControlDevice*>(stub))->placeStructure(creature, x, y, angle);
}

int StructureControlDeviceAdapter::notifyStructurePlaced(CreatureObject* creature, StructureObject* structure) {
	return (static_cast<StructureControlDevice*>(stub))->notifyStructurePlaced(creature, structure);
}

bool StructureControlDeviceAdapter::isStructureControlDevice() {
	return (static_cast<StructureControlDevice*>(stub))->isStructureControlDevice();
}

/*
 *	StructureControlDeviceHelper
 */

StructureControlDeviceHelper* StructureControlDeviceHelper::staticInitializer = StructureControlDeviceHelper::instance();

StructureControlDeviceHelper::StructureControlDeviceHelper() {
	className = "StructureControlDevice";

	Core::getObjectBroker()->registerClass(className, this);
}

void StructureControlDeviceHelper::finalizeHelper() {
	StructureControlDeviceHelper::finalize();
}

DistributedObject* StructureControlDeviceHelper::instantiateObject() {
	return new StructureControlDevice(DummyConstructorParameter::instance());
}

DistributedObjectServant* StructureControlDeviceHelper::instantiateServant() {
	return new StructureControlDeviceImplementation();
}

DistributedObjectPOD* StructureControlDeviceHelper::instantiatePOD() {
	return new StructureControlDevicePOD();
}

DistributedObjectAdapter* StructureControlDeviceHelper::createAdapter(DistributedObjectStub* obj) {
	DistributedObjectAdapter* adapter = new StructureControlDeviceAdapter(static_cast<StructureControlDevice*>(obj));

	obj->_setClassName(className);
	obj->_setClassHelper(this);

	adapter->setStub(obj);

	return adapter;
}

/*
 *	StructureControlDevicePOD
 */

StructureControlDevicePOD::~StructureControlDevicePOD() {
	finalize();
}

StructureControlDevicePOD::StructureControlDevicePOD(void) {
	_className = "StructureControlDevice";
}


void StructureControlDevicePOD::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = StructureControlDevicePOD::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int StructureControlDevicePOD::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = ControlDevicePOD::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;

	return _count;
}

bool StructureControlDevicePOD::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (ControlDevicePOD::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	}

	return false;
}

void StructureControlDevicePOD::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(StructureControlDevicePOD::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

}

void StructureControlDevicePOD::writeObjectCompact(ObjectOutputStream* stream) {
	ControlDevicePOD::writeObjectCompact(stream);


}

