/*
 *	autogen/server/zone/objects/player/sui/Addweapondot/AddWeaponDot.h generated by engine3 IDL compiler 0.70
 */

#ifndef ADDWEAPONDOT_H_
#define ADDWEAPONDOT_H_

#include "engine/core/Core.h"

#include "engine/core/ManagedReference.h"

#include "engine/core/ManagedWeakReference.h"

#include "system/util/Optional.h"

#ifndef likely
#ifdef __GNUC__
#define likely(x)       __builtin_expect(!!(x), 1)
#define unlikely(x)     __builtin_expect(!!(x), 0)
#else
#define likely(x)       (x)
#define unlikely(x)     (x)
#endif
#endif
#include "engine/util/json_utils.h"

namespace server {
namespace zone {
namespace objects {
namespace scene {

class SceneObject;

class SceneObjectPOD;

} // namespace scene
} // namespace objects
} // namespace zone
} // namespace server

using namespace server::zone::objects::scene;

namespace server {
namespace zone {
namespace objects {
namespace creature {

class CreatureObject;

class CreatureObjectPOD;

} // namespace creature
} // namespace objects
} // namespace zone
} // namespace server

using namespace server::zone::objects::creature;

#include "server/zone/packets/ui/SuiCreatePageMessage.h"

#include "engine/lua/LuaObject.h"

#include "engine/service/proto/BaseMessage.h"

#include "server/zone/objects/player/sui/SuiBox.h"

namespace server {
namespace zone {
namespace objects {
namespace player {
namespace sui {
namespace addweapondot {

class AddWeaponDot : public SuiBox {
public:
	AddWeaponDot(CreatureObject* player, unsigned int windowType);

	void addExperience(int exp);

	BaseMessage* generateMessage();

	bool isAddWeaponDot();

	DistributedObjectServant* _getImplementation();
	DistributedObjectServant* _getImplementationForRead() const;

	void _setImplementation(DistributedObjectServant* servant);

protected:
	AddWeaponDot(DummyConstructorParameter* param);

	virtual ~AddWeaponDot();

	friend class AddWeaponDotHelper;
};

} // namespace addweapondot
} // namespace sui
} // namespace player
} // namespace objects
} // namespace zone
} // namespace server

using namespace server::zone::objects::player::sui::addweapondot;

namespace server {
namespace zone {
namespace objects {
namespace player {
namespace sui {
namespace addweapondot {

class AddWeaponDotImplementation : public SuiBoxImplementation {
protected:
	String lblFrom;

	String lblStartingFrom;

	String lblInputFrom;

	String lblTo;

	String lblStartingTo;

	String lblInputTo;

	String convertRatioFrom;

	String convertRatioTo;

public:
	AddWeaponDotImplementation(CreatureObject* player, unsigned int windowType);

	AddWeaponDotImplementation(DummyConstructorParameter* param);

	void addExperience(int exp);

	BaseMessage* generateMessage();

	bool isAddWeaponDot();

	WeakReference<AddWeaponDot*> _this;

	operator const AddWeaponDot*();

	DistributedObjectStub* _getStub();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
protected:
	virtual ~AddWeaponDotImplementation();

	void finalize();

	void _initializeImplementation();

	void _setStub(DistributedObjectStub* stub);

	void lock(bool doLock = true);

	void lock(ManagedObject* obj);

	void rlock(bool doLock = true);

	void wlock(bool doLock = true);

	void wlock(ManagedObject* obj);

	void unlock(bool doLock = true);

	void runlock(bool doLock = true);

	void _serializationHelperMethod();
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);

	friend class AddWeaponDot;
};

class AddWeaponDotAdapter : public SuiBoxAdapter {
public:
	AddWeaponDotAdapter(AddWeaponDot* impl);

	void invokeMethod(sys::uint32 methid, DistributedMethod* method);

	void addExperience(int exp);

	bool isAddWeaponDot();

};

class AddWeaponDotHelper : public DistributedObjectClassHelper, public Singleton<AddWeaponDotHelper> {
	static AddWeaponDotHelper* staticInitializer;

public:
	AddWeaponDotHelper();

	void finalizeHelper();

	DistributedObject* instantiateObject();

	DistributedObjectPOD* instantiatePOD();

	DistributedObjectServant* instantiateServant();

	DistributedObjectAdapter* createAdapter(DistributedObjectStub* obj);

	friend class Singleton<AddWeaponDotHelper>;
};

} // namespace addweapondot
} // namespace sui
} // namespace player
} // namespace objects
} // namespace zone
} // namespace server

using namespace server::zone::objects::player::sui::addweapondot;

namespace server {
namespace zone {
namespace objects {
namespace player {
namespace sui {
namespace addweapondot {

class AddWeaponDotPOD : public SuiBoxPOD {
public:
	Optional<String> lblFrom;

	Optional<String> lblStartingFrom;

	Optional<String> lblInputFrom;

	Optional<String> lblTo;

	Optional<String> lblStartingTo;

	Optional<String> lblInputTo;

	Optional<String> convertRatioFrom;

	Optional<String> convertRatioTo;

	String _className;
	AddWeaponDotPOD();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);
	void writeObjectCompact(ObjectOutputStream* stream);



	virtual ~AddWeaponDotPOD();

};

} // namespace addweapondot
} // namespace sui
} // namespace player
} // namespace objects
} // namespace zone
} // namespace server

using namespace server::zone::objects::player::sui::addweapondot;

#endif /*ADDWEAPONDOTPOD_H_*/
