/*
 *	autogen/server/zone/managers/creature/LairObserver.h generated by engine3 IDL compiler 0.70
 */

#ifndef LAIROBSERVER_H_
#define LAIROBSERVER_H_

#include "engine/core/Core.h"

#include "engine/core/ManagedReference.h"

#include "engine/core/ManagedWeakReference.h"

#include "system/util/Optional.h"

#ifndef likely
#ifdef __GNUC__
#define likely(x)       __builtin_expect(!!(x), 1)
#define unlikely(x)     __builtin_expect(!!(x), 0)
#else
#define likely(x)       (x)
#define unlikely(x)     (x)
#endif
#endif
#include "engine/util/json_utils.h"

namespace server {
namespace zone {
namespace objects {
namespace creature {
namespace ai {

class AiAgent;

class AiAgentPOD;

} // namespace ai
} // namespace creature
} // namespace objects
} // namespace zone
} // namespace server

using namespace server::zone::objects::creature::ai;

namespace server {
namespace zone {
namespace objects {
namespace tangible {

class LairObject;

class LairObjectPOD;

} // namespace tangible
} // namespace objects
} // namespace zone
} // namespace server

using namespace server::zone::objects::tangible;

#include "server/zone/objects/tangible/TangibleObject.h"

#include "system/thread/atomic/AtomicInteger.h"

#include "engine/core/ManagedObject.h"

#include "engine/util/Observable.h"

#include "server/zone/managers/creature/SpawnObserver.h"

#include "system/lang/Time.h"

namespace server {
namespace zone {
namespace managers {
namespace creature {

class LairObserver : public SpawnObserver {
public:
	static const int BABY_SPAWN_CHANCE = 500;

	static const int WILD_LAIR_PASSIVE_MAX = 10;

	static const int SPAWN_TIME_MIN = 1;

	static const int SPAWN_TIME_MAX = 10;

	static const int RESPAWN_TIME_MIN = 120;

	static const int RESPAWN_TIME_MAX = 240;

	static const int PASSIVE_SPAWN_TIME_MIN = 15;

	static const int PASSIVE_SPAWN_TIME_MAX = 20;

	static const int HEAL_CHECK_INTERVAL = 15;

	static const int AGGRO_CHECK_INTERVAL = 30;

	static const int AGGRO_TASK_DELAY = 4;

	static const int SCOUT_SPAWN_CHANCE = 10;

	LairObserver();

	int notifyObserverEvent(unsigned int eventType, Observable* observable, ManagedObject* arg1, long long arg2);

	void notifyDestruction(TangibleObject* lair, TangibleObject* attacker, int condition);

	void checkForHeal(TangibleObject* lair, bool forceNewUpdate = false);

	bool checkForNewSpawns(TangibleObject* lair, TangibleObject* attacker, bool forceSpawn = false);

	void checkForBossSpawn(TangibleObject* lair, TangibleObject* attacker);

	void checkRespawn(LairObject* lair, TangibleObject* attacker);

	void spawnLairMobile(LairObject* lair, int spawnNumber, const String& templateToSpawn, bool spawnPassive = true);

	void doAggro(TangibleObject* lair, TangibleObject* attacker, bool allAttack = false);

	void repopulateLair(TangibleObject* lair);

	bool isLairObserver();

	int getLivingCreatureCount();

	int getMobType();

	int getSpawnNumber();

	DistributedObjectServant* _getImplementation();
	DistributedObjectServant* _getImplementationForRead() const;

	void _setImplementation(DistributedObjectServant* servant);

protected:
	LairObserver(DummyConstructorParameter* param);

	virtual ~LairObserver();

	friend class LairObserverHelper;
};

} // namespace creature
} // namespace managers
} // namespace zone
} // namespace server

using namespace server::zone::managers::creature;

namespace server {
namespace zone {
namespace managers {
namespace creature {

class LairObserverImplementation : public SpawnObserverImplementation {
public:
	static const int BABY_SPAWN_CHANCE = 500;

	static const int WILD_LAIR_PASSIVE_MAX = 10;

	static const int SPAWN_TIME_MIN = 1;

	static const int SPAWN_TIME_MAX = 10;

	static const int RESPAWN_TIME_MIN = 120;

	static const int RESPAWN_TIME_MAX = 240;

	static const int PASSIVE_SPAWN_TIME_MIN = 15;

	static const int PASSIVE_SPAWN_TIME_MAX = 20;

	static const int HEAL_CHECK_INTERVAL = 15;

	static const int AGGRO_CHECK_INTERVAL = 30;

	static const int AGGRO_TASK_DELAY = 4;

	static const int SCOUT_SPAWN_CHANCE = 10;

protected:
	AtomicInteger spawnNumber;

	AtomicInteger bossesSpawned;

	Time lastHealTime;

	Time lastAggroTime;

	unsigned long long scoutCreatureId;

public:
	LairObserverImplementation();

	LairObserverImplementation(DummyConstructorParameter* param);

	int notifyObserverEvent(unsigned int eventType, Observable* observable, ManagedObject* arg1, long long arg2);

	void notifyDestruction(TangibleObject* lair, TangibleObject* attacker, int condition);

	virtual void checkForHeal(TangibleObject* lair, bool forceNewUpdate = false);

	virtual bool checkForNewSpawns(TangibleObject* lair, TangibleObject* attacker, bool forceSpawn = false);

	void checkForBossSpawn(TangibleObject* lair, TangibleObject* attacker);

	void checkRespawn(LairObject* lair, TangibleObject* attacker);

	virtual void spawnLairMobile(LairObject* lair, int spawnNumber, const String& templateToSpawn, bool spawnPassive = true);

	void doAggro(TangibleObject* lair, TangibleObject* attacker, bool allAttack = false);

	void repopulateLair(TangibleObject* lair);

	bool isLairObserver();

	int getLivingCreatureCount();

	int getMobType();

	int getSpawnNumber();

	WeakReference<LairObserver*> _this;

	operator const LairObserver*();

	DistributedObjectStub* _getStub();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
protected:
	virtual ~LairObserverImplementation();

	void finalize();

	void _initializeImplementation();

	void _setStub(DistributedObjectStub* stub);

	void lock(bool doLock = true);

	void lock(ManagedObject* obj);

	void rlock(bool doLock = true);

	void wlock(bool doLock = true);

	void wlock(ManagedObject* obj);

	void unlock(bool doLock = true);

	void runlock(bool doLock = true);

	void _serializationHelperMethod();
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);

	friend class LairObserver;
};

class LairObserverAdapter : public SpawnObserverAdapter {
public:
	LairObserverAdapter(LairObserver* impl);

	void invokeMethod(sys::uint32 methid, DistributedMethod* method);

	int notifyObserverEvent(unsigned int eventType, Observable* observable, ManagedObject* arg1, long long arg2);

	void notifyDestruction(TangibleObject* lair, TangibleObject* attacker, int condition);

	void checkForHeal(TangibleObject* lair, bool forceNewUpdate);

	bool checkForNewSpawns(TangibleObject* lair, TangibleObject* attacker, bool forceSpawn);

	void checkForBossSpawn(TangibleObject* lair, TangibleObject* attacker);

	void checkRespawn(LairObject* lair, TangibleObject* attacker);

	void spawnLairMobile(LairObject* lair, int spawnNumber, const String& templateToSpawn, bool spawnPassive);

	void doAggro(TangibleObject* lair, TangibleObject* attacker, bool allAttack);

	void repopulateLair(TangibleObject* lair);

	bool isLairObserver();

	int getLivingCreatureCount();

	int getMobType();

	int getSpawnNumber();

};

class LairObserverHelper : public DistributedObjectClassHelper, public Singleton<LairObserverHelper> {
	static LairObserverHelper* staticInitializer;

public:
	LairObserverHelper();

	void finalizeHelper();

	DistributedObject* instantiateObject();

	DistributedObjectPOD* instantiatePOD();

	DistributedObjectServant* instantiateServant();

	DistributedObjectAdapter* createAdapter(DistributedObjectStub* obj);

	friend class Singleton<LairObserverHelper>;
};

} // namespace creature
} // namespace managers
} // namespace zone
} // namespace server

using namespace server::zone::managers::creature;

namespace server {
namespace zone {
namespace managers {
namespace creature {

class LairObserverPOD : public SpawnObserverPOD {
public:
	Optional<AtomicInteger> spawnNumber;

	Optional<AtomicInteger> bossesSpawned;

	Optional<unsigned long long> scoutCreatureId;

	String _className;
	LairObserverPOD();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);
	void writeObjectCompact(ObjectOutputStream* stream);



	virtual ~LairObserverPOD();

};

} // namespace creature
} // namespace managers
} // namespace zone
} // namespace server

using namespace server::zone::managers::creature;

#endif /*LAIROBSERVERPOD_H_*/
