/*
 *	autogen/server/zone/objects/player/sui/deconstructweapon/DeconstructWeapon.cpp generated by engine3 IDL compiler 0.70
 */

#include "DeconstructWeapon.h"

#include "server/zone/objects/scene/SceneObject.h"

#include "server/zone/objects/creature/CreatureObject.h"

/*
 *	DeconstructWeaponStub
 */

enum {RPC_ISDECONSTRUCTWEAPON__};

DeconstructWeapon::DeconstructWeapon(CreatureObject* player, unsigned int windowType) : SuiBox(DummyConstructorParameter::instance()) {
	DeconstructWeaponImplementation* _implementation = new DeconstructWeaponImplementation(player, windowType);
	_impl = _implementation;
	_impl->_setStub(this);
	_setClassName("DeconstructWeapon");
}

DeconstructWeapon::DeconstructWeapon(DummyConstructorParameter* param) : SuiBox(param) {
	_setClassName("DeconstructWeapon");
}

DeconstructWeapon::~DeconstructWeapon() {
}



BaseMessage* DeconstructWeapon::generateMessage() {
	DeconstructWeaponImplementation* _implementation = static_cast<DeconstructWeaponImplementation*>(_getImplementation());
	if (unlikely(_implementation == nullptr)) {
		throw ObjectNotLocalException(this);

	} else {
		return _implementation->generateMessage();
	}
}

bool DeconstructWeapon::isDeconstructWeapon() {
	DeconstructWeaponImplementation* _implementation = static_cast<DeconstructWeaponImplementation*>(_getImplementation());
	if (unlikely(_implementation == nullptr)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_ISDECONSTRUCTWEAPON__);

		return method.executeWithBooleanReturn();
	} else {
		return _implementation->isDeconstructWeapon();
	}
}

DistributedObjectServant* DeconstructWeapon::_getImplementation() {

	 if (!_updated) _updated = true;
	return _impl;
}

DistributedObjectServant* DeconstructWeapon::_getImplementationForRead() const {
	return _impl;
}

void DeconstructWeapon::_setImplementation(DistributedObjectServant* servant) {
	_impl = servant;
}

/*
 *	DeconstructWeaponImplementation
 */

DeconstructWeaponImplementation::DeconstructWeaponImplementation(DummyConstructorParameter* param) : SuiBoxImplementation(param) {
	_initializeImplementation();
}


DeconstructWeaponImplementation::~DeconstructWeaponImplementation() {
}


void DeconstructWeaponImplementation::finalize() {
}

void DeconstructWeaponImplementation::_initializeImplementation() {
	_setClassHelper(DeconstructWeaponHelper::instance());

	_this = nullptr;

	_serializationHelperMethod();
}

void DeconstructWeaponImplementation::_setStub(DistributedObjectStub* stub) {
	_this = static_cast<DeconstructWeapon*>(stub);
	SuiBoxImplementation::_setStub(stub);
}

DistributedObjectStub* DeconstructWeaponImplementation::_getStub() {
	return _this.get();
}

DeconstructWeaponImplementation::operator const DeconstructWeapon*() {
	return _this.get();
}

void DeconstructWeaponImplementation::lock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->lock(doLock);
}

void DeconstructWeaponImplementation::lock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->lock(obj);
}

void DeconstructWeaponImplementation::rlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->rlock(doLock);
}

void DeconstructWeaponImplementation::wlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->wlock(doLock);
}

void DeconstructWeaponImplementation::wlock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->wlock(obj);
}

void DeconstructWeaponImplementation::unlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->unlock(doLock);
}

void DeconstructWeaponImplementation::runlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->runlock(doLock);
}

void DeconstructWeaponImplementation::_serializationHelperMethod() {
	SuiBoxImplementation::_serializationHelperMethod();

	_setClassName("DeconstructWeapon");

}

void DeconstructWeaponImplementation::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(DeconstructWeaponImplementation::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

	initializeTransientMembers();
}

bool DeconstructWeaponImplementation::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (SuiBoxImplementation::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	}

	return false;
}

void DeconstructWeaponImplementation::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = DeconstructWeaponImplementation::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int DeconstructWeaponImplementation::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = SuiBoxImplementation::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;

	return _count;
}

DeconstructWeaponImplementation::DeconstructWeaponImplementation(CreatureObject* player, unsigned int windowType) : SuiBoxImplementation(player, windowType, SuiBoxImplementation::DECONSTRUCTWEAPON) {
	_initializeImplementation();
}

bool DeconstructWeaponImplementation::isDeconstructWeapon() {
	// server/zone/objects/player/sui/deconstructweapon/DeconstructWeapon.idl():  		return true;
	return true;
}

/*
 *	DeconstructWeaponAdapter
 */


#include "engine/orb/messages/InvokeMethodMessage.h"


DeconstructWeaponAdapter::DeconstructWeaponAdapter(DeconstructWeapon* obj) : SuiBoxAdapter(obj) {
}

void DeconstructWeaponAdapter::invokeMethod(uint32 methid, DistributedMethod* inv) {
	DOBMessage* resp = inv->getInvocationMessage();

	switch (methid) {
	case RPC_ISDECONSTRUCTWEAPON__:
		{
			
			bool _m_res = isDeconstructWeapon();
			resp->insertBoolean(_m_res);
		}
		break;
	default:
		SuiBoxAdapter::invokeMethod(methid, inv);
	}
}

bool DeconstructWeaponAdapter::isDeconstructWeapon() {
	return (static_cast<DeconstructWeapon*>(stub))->isDeconstructWeapon();
}

/*
 *	DeconstructWeaponHelper
 */

DeconstructWeaponHelper* DeconstructWeaponHelper::staticInitializer = DeconstructWeaponHelper::instance();

DeconstructWeaponHelper::DeconstructWeaponHelper() {
	className = "DeconstructWeapon";

	Core::getObjectBroker()->registerClass(className, this);
}

void DeconstructWeaponHelper::finalizeHelper() {
	DeconstructWeaponHelper::finalize();
}

DistributedObject* DeconstructWeaponHelper::instantiateObject() {
	return new DeconstructWeapon(DummyConstructorParameter::instance());
}

DistributedObjectServant* DeconstructWeaponHelper::instantiateServant() {
	return new DeconstructWeaponImplementation(DummyConstructorParameter::instance());
}

DistributedObjectPOD* DeconstructWeaponHelper::instantiatePOD() {
	return new DeconstructWeaponPOD();
}

DistributedObjectAdapter* DeconstructWeaponHelper::createAdapter(DistributedObjectStub* obj) {
	DistributedObjectAdapter* adapter = new DeconstructWeaponAdapter(static_cast<DeconstructWeapon*>(obj));

	obj->_setClassName(className);
	obj->_setClassHelper(this);

	adapter->setStub(obj);

	return adapter;
}

/*
 *	DeconstructWeaponPOD
 */

DeconstructWeaponPOD::~DeconstructWeaponPOD() {
	finalize();
}

DeconstructWeaponPOD::DeconstructWeaponPOD(void) {
	_className = "DeconstructWeapon";
}


void DeconstructWeaponPOD::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = DeconstructWeaponPOD::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int DeconstructWeaponPOD::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = SuiBoxPOD::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;

	return _count;
}

bool DeconstructWeaponPOD::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (SuiBoxPOD::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	}

	return false;
}

void DeconstructWeaponPOD::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(DeconstructWeaponPOD::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

}

void DeconstructWeaponPOD::writeObjectCompact(ObjectOutputStream* stream) {
	SuiBoxPOD::writeObjectCompact(stream);


}

