/*
 *	autogen/server/zone/objects/tangible/misc/VendorToken.cpp generated by engine3 IDL compiler 0.70
 */

#include "VendorToken.h"

#include "server/zone/objects/scene/SceneObject.h"

#include "server/zone/Zone.h"

#include "server/zone/objects/creature/CreatureObject.h"

#include "server/zone/ZoneServer.h"

#include "server/zone/packets/object/ObjectMenuResponse.h"

/*
 *	VendorTokenStub
 */

enum {RPC_HANDLEOBJECTMENUSELECT__CREATUREOBJECT_BYTE_ = 2970789320,RPC_CANADDOBJECT__SCENEOBJECT_INT_STRING_,RPC_NOTIFYOBJECTINSERTED__SCENEOBJECT_,RPC_CHECKCONTAINERPERMISSION__CREATUREOBJECT_SHORT_};

VendorToken::VendorToken() : TangibleObject(DummyConstructorParameter::instance()) {
	VendorTokenImplementation* _implementation = new VendorTokenImplementation();
	_impl = _implementation;
	_impl->_setStub(this);
	_setClassName("VendorToken");
}

VendorToken::VendorToken(DummyConstructorParameter* param) : TangibleObject(param) {
	_setClassName("VendorToken");
}

VendorToken::~VendorToken() {
}



int VendorToken::handleObjectMenuSelect(CreatureObject* player, byte selectedID) {
	VendorTokenImplementation* _implementation = static_cast<VendorTokenImplementation*>(_getImplementation());
	if (unlikely(_implementation == nullptr)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_HANDLEOBJECTMENUSELECT__CREATUREOBJECT_BYTE_);
		method.addObjectParameter(player);
		method.addByteParameter(selectedID);

		return method.executeWithSignedIntReturn();
	} else {
		assert(this->isLockedByCurrentThread());
		assert((player == nullptr) || player->isLockedByCurrentThread());
		return _implementation->handleObjectMenuSelect(player, selectedID);
	}
}

void VendorToken::fillObjectMenuResponse(ObjectMenuResponse* menuResponse, CreatureObject* player) {
	VendorTokenImplementation* _implementation = static_cast<VendorTokenImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == nullptr)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->fillObjectMenuResponse(menuResponse, player);
	}
}

int VendorToken::canAddObject(SceneObject* object, int containmentType, String& errorDescription) {
	VendorTokenImplementation* _implementation = static_cast<VendorTokenImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == nullptr)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_CANADDOBJECT__SCENEOBJECT_INT_STRING_);
		method.addObjectParameter(object);
		method.addSignedIntParameter(containmentType);
		method.addAsciiParameter(errorDescription);

		return method.executeWithSignedIntReturn();
	} else {
		return _implementation->canAddObject(object, containmentType, errorDescription);
	}
}

int VendorToken::notifyObjectInserted(SceneObject* object) {
	VendorTokenImplementation* _implementation = static_cast<VendorTokenImplementation*>(_getImplementation());
	if (unlikely(_implementation == nullptr)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_NOTIFYOBJECTINSERTED__SCENEOBJECT_);
		method.addObjectParameter(object);

		return method.executeWithSignedIntReturn();
	} else {
		return _implementation->notifyObjectInserted(object);
	}
}

byte VendorToken::checkContainerPermission(CreatureObject* player, unsigned short permission) {
	VendorTokenImplementation* _implementation = static_cast<VendorTokenImplementation*>(_getImplementation());
	if (unlikely(_implementation == nullptr)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_CHECKCONTAINERPERMISSION__CREATUREOBJECT_SHORT_);
		method.addObjectParameter(player);
		method.addUnsignedShortParameter(permission);

		return method.executeWithByteReturn();
	} else {
		return _implementation->checkContainerPermission(player, permission);
	}
}

DistributedObjectServant* VendorToken::_getImplementation() {

	 if (!_updated) _updated = true;
	return _impl;
}

DistributedObjectServant* VendorToken::_getImplementationForRead() const {
	return _impl;
}

void VendorToken::_setImplementation(DistributedObjectServant* servant) {
	_impl = servant;
}

/*
 *	VendorTokenImplementation
 */

VendorTokenImplementation::VendorTokenImplementation(DummyConstructorParameter* param) : TangibleObjectImplementation(param) {
	_initializeImplementation();
}


VendorTokenImplementation::~VendorTokenImplementation() {
}


void VendorTokenImplementation::finalize() {
}

void VendorTokenImplementation::_initializeImplementation() {
	_setClassHelper(VendorTokenHelper::instance());

	_this = nullptr;

	_serializationHelperMethod();
}

void VendorTokenImplementation::_setStub(DistributedObjectStub* stub) {
	_this = static_cast<VendorToken*>(stub);
	TangibleObjectImplementation::_setStub(stub);
}

DistributedObjectStub* VendorTokenImplementation::_getStub() {
	return _this.get();
}

VendorTokenImplementation::operator const VendorToken*() {
	return _this.get();
}

void VendorTokenImplementation::lock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->lock(doLock);
}

void VendorTokenImplementation::lock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->lock(obj);
}

void VendorTokenImplementation::rlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->rlock(doLock);
}

void VendorTokenImplementation::wlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->wlock(doLock);
}

void VendorTokenImplementation::wlock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->wlock(obj);
}

void VendorTokenImplementation::unlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->unlock(doLock);
}

void VendorTokenImplementation::runlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->runlock(doLock);
}

void VendorTokenImplementation::_serializationHelperMethod() {
	TangibleObjectImplementation::_serializationHelperMethod();

	_setClassName("VendorToken");

}

void VendorTokenImplementation::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(VendorTokenImplementation::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

	initializeTransientMembers();
}

bool VendorTokenImplementation::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (TangibleObjectImplementation::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	}

	return false;
}

void VendorTokenImplementation::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = VendorTokenImplementation::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int VendorTokenImplementation::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = TangibleObjectImplementation::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;

	return _count;
}

VendorTokenImplementation::VendorTokenImplementation() {
	_initializeImplementation();
	// server/zone/objects/tangible/misc/VendorToken.idl():  		setLoggingName("VendorToken");
	setLoggingName("VendorToken");
}

/*
 *	VendorTokenAdapter
 */


#include "engine/orb/messages/InvokeMethodMessage.h"


VendorTokenAdapter::VendorTokenAdapter(VendorToken* obj) : TangibleObjectAdapter(obj) {
}

void VendorTokenAdapter::invokeMethod(uint32 methid, DistributedMethod* inv) {
	DOBMessage* resp = inv->getInvocationMessage();

	switch (methid) {
	case RPC_HANDLEOBJECTMENUSELECT__CREATUREOBJECT_BYTE_:
		{
			CreatureObject* player = static_cast<CreatureObject*>(inv->getObjectParameter());
			byte selectedID = inv->getByteParameter();
			
			int _m_res = handleObjectMenuSelect(player, selectedID);
			resp->insertSignedInt(_m_res);
		}
		break;
	case RPC_CANADDOBJECT__SCENEOBJECT_INT_STRING_:
		{
			SceneObject* object = static_cast<SceneObject*>(inv->getObjectParameter());
			int containmentType = inv->getSignedIntParameter();
			String errorDescription; inv->getAsciiParameter(errorDescription);
			
			int _m_res = canAddObject(object, containmentType, errorDescription);
			resp->insertSignedInt(_m_res);
		}
		break;
	case RPC_NOTIFYOBJECTINSERTED__SCENEOBJECT_:
		{
			SceneObject* object = static_cast<SceneObject*>(inv->getObjectParameter());
			
			int _m_res = notifyObjectInserted(object);
			resp->insertSignedInt(_m_res);
		}
		break;
	case RPC_CHECKCONTAINERPERMISSION__CREATUREOBJECT_SHORT_:
		{
			CreatureObject* player = static_cast<CreatureObject*>(inv->getObjectParameter());
			unsigned short permission = inv->getUnsignedShortParameter();
			
			byte _m_res = checkContainerPermission(player, permission);
			resp->insertByte(_m_res);
		}
		break;
	default:
		TangibleObjectAdapter::invokeMethod(methid, inv);
	}
}

int VendorTokenAdapter::handleObjectMenuSelect(CreatureObject* player, byte selectedID) {
	return (static_cast<VendorToken*>(stub))->handleObjectMenuSelect(player, selectedID);
}

int VendorTokenAdapter::canAddObject(SceneObject* object, int containmentType, String& errorDescription) {
	return (static_cast<VendorToken*>(stub))->canAddObject(object, containmentType, errorDescription);
}

int VendorTokenAdapter::notifyObjectInserted(SceneObject* object) {
	return (static_cast<VendorToken*>(stub))->notifyObjectInserted(object);
}

byte VendorTokenAdapter::checkContainerPermission(CreatureObject* player, unsigned short permission) {
	return (static_cast<VendorToken*>(stub))->checkContainerPermission(player, permission);
}

/*
 *	VendorTokenHelper
 */

VendorTokenHelper* VendorTokenHelper::staticInitializer = VendorTokenHelper::instance();

VendorTokenHelper::VendorTokenHelper() {
	className = "VendorToken";

	Core::getObjectBroker()->registerClass(className, this);
}

void VendorTokenHelper::finalizeHelper() {
	VendorTokenHelper::finalize();
}

DistributedObject* VendorTokenHelper::instantiateObject() {
	return new VendorToken(DummyConstructorParameter::instance());
}

DistributedObjectServant* VendorTokenHelper::instantiateServant() {
	return new VendorTokenImplementation();
}

DistributedObjectPOD* VendorTokenHelper::instantiatePOD() {
	return new VendorTokenPOD();
}

DistributedObjectAdapter* VendorTokenHelper::createAdapter(DistributedObjectStub* obj) {
	DistributedObjectAdapter* adapter = new VendorTokenAdapter(static_cast<VendorToken*>(obj));

	obj->_setClassName(className);
	obj->_setClassHelper(this);

	adapter->setStub(obj);

	return adapter;
}

const char LuaVendorToken::className[] = "LuaVendorToken";

Luna<LuaVendorToken>::RegType LuaVendorToken::Register[] = {
	{ "_setObject", &LuaVendorToken::_setObject },
	{ "_getObject", &LuaVendorToken::_getObject },
	{ "handleObjectMenuSelect", &LuaVendorToken::handleObjectMenuSelect },
	{ "fillObjectMenuResponse", &LuaVendorToken::fillObjectMenuResponse },
	{ "canAddObject", &LuaVendorToken::canAddObject },
	{ "notifyObjectInserted", &LuaVendorToken::notifyObjectInserted },
	{ "checkContainerPermission", &LuaVendorToken::checkContainerPermission },
	{ 0, 0 }
};

LuaVendorToken::LuaVendorToken(lua_State *L) {
	realObject = static_cast<VendorToken*>(lua_touserdata(L, 1));
}

LuaVendorToken::~LuaVendorToken() {
}

int LuaVendorToken::_setObject(lua_State* L) {
	realObject = static_cast<VendorToken*>(lua_touserdata(L, -1));

	return 0;
}

int LuaVendorToken::_getObject(lua_State* L) {
	lua_pushlightuserdata(L, realObject.get());

	return 1;
}

int LuaVendorToken::handleObjectMenuSelect(lua_State *L) {
	int parameterCount = lua_gettop(L) - 1;
	
	if (lua_isnumber(L, -1)) {
		if (lua_isuserdata(L, -2)) {
			if (parameterCount == 2) {
				CreatureObject* player = static_cast<CreatureObject*>(lua_touserdata(L, -2));
				byte selectedID = lua_tointeger(L, -1);

				Locker _guard(realObject);

				int result = realObject->handleObjectMenuSelect(player, selectedID);

				lua_pushinteger(L, result);
				return 1;
			} else {
				throw LuaCallbackException(L, "invalid argument count " + String::valueOf(parameterCount) + " for lua method 'VendorToken:handleObjectMenuSelect(userdata, integer)'");
			}
		} else {
			throw LuaCallbackException(L, "invalid argument at 1 for lua method 'VendorToken:handleObjectMenuSelect(userdata, integer)'");
		}
	} else {
		throw LuaCallbackException(L, "invalid argument at 0 for lua method 'VendorToken:handleObjectMenuSelect(userdata, integer)'");
	}
	return 0;
}

int LuaVendorToken::fillObjectMenuResponse(lua_State *L) {
	int parameterCount = lua_gettop(L) - 1;
	
	if (lua_isuserdata(L, -1)) {
		if (lua_isuserdata(L, -2)) {
			if (parameterCount == 2) {
				ObjectMenuResponse* menuResponse = static_cast<ObjectMenuResponse*>(lua_touserdata(L, -2));
				CreatureObject* player = static_cast<CreatureObject*>(lua_touserdata(L, -1));

				realObject->fillObjectMenuResponse(menuResponse, player);

				return 0;
			} else {
				throw LuaCallbackException(L, "invalid argument count " + String::valueOf(parameterCount) + " for lua method 'VendorToken:fillObjectMenuResponse(userdata, userdata)'");
			}
		} else {
			throw LuaCallbackException(L, "invalid argument at 1 for lua method 'VendorToken:fillObjectMenuResponse(userdata, userdata)'");
		}
	} else {
		throw LuaCallbackException(L, "invalid argument at 0 for lua method 'VendorToken:fillObjectMenuResponse(userdata, userdata)'");
	}
	return 0;
}

int LuaVendorToken::canAddObject(lua_State *L) {
	int parameterCount = lua_gettop(L) - 1;
	
	if (lua_isstring(L, -1)) {
		if (lua_isnumber(L, -2)) {
			if (lua_isuserdata(L, -3)) {
				if (parameterCount == 3) {
					SceneObject* object = static_cast<SceneObject*>(lua_touserdata(L, -3));
					int containmentType = lua_tointeger(L, -2);
					String errorDescription = lua_tostring(L, -1);

					int result = realObject->canAddObject(object, containmentType, errorDescription);

					lua_pushinteger(L, result);
					return 1;
				} else {
					throw LuaCallbackException(L, "invalid argument count " + String::valueOf(parameterCount) + " for lua method 'VendorToken:canAddObject(userdata, integer, string)'");
				}
			} else {
				throw LuaCallbackException(L, "invalid argument at 2 for lua method 'VendorToken:canAddObject(userdata, integer, string)'");
			}
		} else {
			throw LuaCallbackException(L, "invalid argument at 1 for lua method 'VendorToken:canAddObject(userdata, integer, string)'");
		}
	} else {
		throw LuaCallbackException(L, "invalid argument at 0 for lua method 'VendorToken:canAddObject(userdata, integer, string)'");
	}
	return 0;
}

int LuaVendorToken::notifyObjectInserted(lua_State *L) {
	int parameterCount = lua_gettop(L) - 1;
	
	if (lua_isuserdata(L, -1)) {
		if (parameterCount == 1) {
			SceneObject* object = static_cast<SceneObject*>(lua_touserdata(L, -1));

			int result = realObject->notifyObjectInserted(object);

			lua_pushinteger(L, result);
			return 1;
		} else {
			throw LuaCallbackException(L, "invalid argument count " + String::valueOf(parameterCount) + " for lua method 'VendorToken:notifyObjectInserted(userdata)'");
		}
	} else {
		throw LuaCallbackException(L, "invalid argument at 0 for lua method 'VendorToken:notifyObjectInserted(userdata)'");
	}
	return 0;
}

int LuaVendorToken::checkContainerPermission(lua_State *L) {
	int parameterCount = lua_gettop(L) - 1;
	
	if (lua_isnumber(L, -1)) {
		if (lua_isuserdata(L, -2)) {
			if (parameterCount == 2) {
				CreatureObject* player = static_cast<CreatureObject*>(lua_touserdata(L, -2));
				unsigned short permission = lua_tointeger(L, -1);

				byte result = realObject->checkContainerPermission(player, permission);

				lua_pushinteger(L, result);
				return 1;
			} else {
				throw LuaCallbackException(L, "invalid argument count " + String::valueOf(parameterCount) + " for lua method 'VendorToken:checkContainerPermission(userdata, integer)'");
			}
		} else {
			throw LuaCallbackException(L, "invalid argument at 1 for lua method 'VendorToken:checkContainerPermission(userdata, integer)'");
		}
	} else {
		throw LuaCallbackException(L, "invalid argument at 0 for lua method 'VendorToken:checkContainerPermission(userdata, integer)'");
	}
	return 0;
}

/*
 *	VendorTokenPOD
 */

VendorTokenPOD::~VendorTokenPOD() {
	finalize();
}

VendorTokenPOD::VendorTokenPOD(void) {
	_className = "VendorToken";
}


void VendorTokenPOD::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = VendorTokenPOD::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int VendorTokenPOD::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = TangibleObjectPOD::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;

	return _count;
}

bool VendorTokenPOD::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (TangibleObjectPOD::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	}

	return false;
}

void VendorTokenPOD::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(VendorTokenPOD::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

}

void VendorTokenPOD::writeObjectCompact(ObjectOutputStream* stream) {
	TangibleObjectPOD::writeObjectCompact(stream);


}

